/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/array-validations-example.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-array-validations-example";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Array Validations Example", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-example-added-empty-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-001-example-added-empty-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-example-added-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-002-example-added-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-example-removed-empty-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-003-example-removed-empty-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-example-removed-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-004-example-removed-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-example-replaced-empty-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-005-example-replaced-empty-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-example-replaced-array-to-empty", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-006-example-replaced-array-to-empty`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-example-replaced-array-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-validations-example--case-007-example-replaced-array-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
