/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/extended-default-samples.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-extended-default-samples";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Extended Default Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-default-added-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default-samples--case-001-default-added-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-default-removed-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default-samples--case-002-default-removed-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-default-replaced-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default-samples--case-003-default-replaced-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-default-replaced-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default-samples--case-004-default-replaced-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
