/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/extended-array.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";
import { waitForJsonSchemaDiffsViewer } from "../service/viewer-waits";

const META_ID = "json-schema-diffs-suite-array-items-and-additional-items-extended-array";

describe("JSON Schema Diffs Suite/Array Items And Additional Items/Extended Array", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-additional-items-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-001-additional-items-added`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-additional-items-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-002-additional-items-removed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-additional-items-type-changed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-003-additional-items-type-changed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-items-schema-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-004-items-schema-to-array`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-tuple-item-appended", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-005-tuple-item-appended`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-tuple-item-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-006-tuple-item-removed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-items-schema-description-changed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-array-items-and-additional-items-extended-array--case-007-items-schema-description-changed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
