/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/extended-array-samples.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-extended-array-samples";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-testid="json-schema-next-diffs-viewer"]', { visible: true });
  await page.waitForFunction(() => {
    for (const selector of ['[data-name="JsonNode"]', '[data-testid="json-schema-combiner-node-viewer"]']) {
      const element = document.querySelector(selector);
      if (!element) {
        continue;
      }
      const rect = element.getBoundingClientRect();
      if (rect.width > 0 && rect.height > 0) {
        return true;
      }
    }
    return false;
  });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Extended Array Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-additional-items-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-001-additional-items-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-additional-items-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-002-additional-items-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-additional-items-type-changed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-003-additional-items-type-changed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-items-schema-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-004-items-schema-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-tuple-item-appended", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-005-tuple-item-appended`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-tuple-item-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-006-tuple-item-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-items-schema-description-changed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-007-items-schema-description-changed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-unique-items-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-008-unique-items-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-unique-items-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-array-samples--case-009-unique-items-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
