/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/extended-combiners-one-level-samples.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-extended-combiners-one-level-samples";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-testid="json-schema-next-diffs-viewer"]', { visible: true });
  await page.waitForFunction(() => {
    for (const selector of ['[data-name="JsonNode"]', '[data-testid="json-schema-combiner-node-viewer"]']) {
      const element = document.querySelector(selector);
      if (!element) {
        continue;
      }
      const rect = element.getBoundingClientRect();
      if (rect.width > 0 && rect.height > 0) {
        return true;
      }
    }
    return false;
  });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Extended Combiners One Level Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-append-variant-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-001-append-variant-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-append-variant-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-002-append-variant-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-append-variant-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-003-append-variant-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-remove-variant-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-004-remove-variant-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-remove-variant-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-005-remove-variant-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-remove-variant-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-006-remove-variant-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-change-variant-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-007-change-variant-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-change-variant-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-008-change-variant-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-change-variant-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-009-change-variant-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-append-variant-nested-combiner", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-010-append-variant-nested-combiner`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-remove-variant-nested-combiner", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-combiners-one-level-samples--case-011-remove-variant-nested-combiner`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
