/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/extended-default.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";
import { waitForJsonSchemaDiffsViewer } from "../service/viewer-waits";

const META_ID = "json-schema-diffs-suite-extended-default";

describe("JSON Schema Diffs Suite/Extended Default", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-default-added-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default--case-001-default-added-string`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-default-removed-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default--case-002-default-removed-string`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-default-replaced-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default--case-003-default-replaced-string`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-default-replaced-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-extended-default--case-004-default-replaced-boolean`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
