/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/number-validation-multiple-of.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";
import { waitForJsonSchemaDiffsViewer } from "../service/viewer-waits";

const META_ID = "json-schema-diffs-suite-number-validation-multiple-of";

describe("JSON Schema Diffs Suite/Number Validation/Multiple Of", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-multiple-of-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-multiple-of--case-001-multiple-of-added`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-multiple-of-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-multiple-of--case-002-multiple-of-removed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-multiple-of-replaced", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-multiple-of--case-003-multiple-of-replaced`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
