/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/number-validation-value-range-samples.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-number-validation-value-range-samples";

async function waitForJsonSchemaNextDiffsViewer() {
  await page.waitForSelector('[data-testid="json-schema-next-diffs-viewer"]', { visible: true });
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Number Validation Value Range Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-minimum-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-001-minimum-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-minimum-added-with-exclusive-minimum-true", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-002-minimum-added-with-exclusive-minimum-true`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-exclusive-minimum-numeric-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-003-exclusive-minimum-numeric-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-minimum-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-004-minimum-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-minimum-with-exclusive-minimum-true-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-005-minimum-with-exclusive-minimum-true-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-exclusive-minimum-numeric-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-006-exclusive-minimum-numeric-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-exclusive-minimum-false-to-true", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-007-exclusive-minimum-false-to-true`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-exclusive-minimum-true-to-false", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-008-exclusive-minimum-true-to-false`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-maximum-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-009-maximum-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-maximum-added-with-exclusive-maximum-true", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-010-maximum-added-with-exclusive-maximum-true`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-exclusive-maximum-numeric-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-011-exclusive-maximum-numeric-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-maximum-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-012-maximum-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-maximum-with-exclusive-maximum-true-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-013-maximum-with-exclusive-maximum-true-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("014-exclusive-maximum-numeric-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-014-exclusive-maximum-numeric-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("015-exclusive-maximum-false-to-true", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-015-exclusive-maximum-false-to-true`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("016-exclusive-maximum-true-to-false", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-016-exclusive-maximum-true-to-false`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("017-minimum-maximum-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-017-minimum-maximum-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("018-minimum-inclusive-maximum-exclusive-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-018-minimum-inclusive-maximum-exclusive-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("019-minimum-exclusive-maximum-inclusive-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-019-minimum-exclusive-maximum-inclusive-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("020-minimum-maximum-both-exclusive-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-020-minimum-maximum-both-exclusive-added`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("021-minimum-maximum-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-021-minimum-maximum-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("022-minimum-inclusive-maximum-exclusive-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-022-minimum-inclusive-maximum-exclusive-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("023-minimum-exclusive-maximum-inclusive-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-023-minimum-exclusive-maximum-inclusive-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("024-minimum-maximum-both-exclusive-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-024-minimum-maximum-both-exclusive-removed`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("025-min-ex-max-in-min-ex-to-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-025-min-ex-max-in-min-ex-to-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("026-min-ex-max-in-max-in-to-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-026-min-ex-max-in-max-in-to-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("027-min-in-max-ex-min-in-to-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-027-min-in-max-ex-min-in-to-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("028-min-in-max-ex-max-ex-to-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-028-min-in-max-ex-max-ex-to-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("029-min-in-max-in-min-in-to-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-029-min-in-max-in-min-in-to-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("030-min-in-max-in-max-in-to-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-030-min-in-max-in-max-in-to-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("031-min-in-max-in-both-to-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-031-min-in-max-in-both-to-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("032-min-ex-max-ex-min-ex-to-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-032-min-ex-max-ex-min-ex-to-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("033-min-ex-max-ex-max-ex-to-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-033-min-ex-max-ex-max-ex-to-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("034-min-ex-max-ex-both-to-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-034-min-ex-max-ex-both-to-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("035-unchanged-minimum-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-035-unchanged-minimum-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("036-unchanged-minimum-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-036-unchanged-minimum-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("037-unchanged-maximum-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-037-unchanged-maximum-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("038-unchanged-maximum-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-038-unchanged-maximum-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("039-unchanged-min-max-inclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-039-unchanged-min-max-inclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("040-unchanged-min-inclusive-max-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-040-unchanged-min-inclusive-max-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("041-unchanged-min-max-both-exclusive", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-041-unchanged-min-max-both-exclusive`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("042-min-in-add-max-in", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-042-min-in-add-max-in`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("043-min-in-add-max-ex", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-043-min-in-add-max-ex`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("044-min-ex-add-max-in", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-044-min-ex-add-max-in`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("045-min-ex-add-max-ex", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-045-min-ex-add-max-ex`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("046-max-in-add-min-in", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-046-max-in-add-min-in`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("047-max-in-add-min-ex", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-047-max-in-add-min-ex`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("048-max-ex-add-min-in", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-048-max-ex-add-min-in`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("049-max-ex-add-min-ex", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-049-max-ex-add-min-ex`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("050-min-in-max-in-remove-minimum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-050-min-in-max-in-remove-minimum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("051-min-in-max-in-remove-maximum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-051-min-in-max-in-remove-maximum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("052-min-ex-max-ex-remove-minimum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-052-min-ex-max-ex-remove-minimum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("053-min-ex-max-ex-remove-maximum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-053-min-ex-max-ex-remove-maximum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("054-min-in-max-ex-remove-minimum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-054-min-in-max-ex-remove-minimum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("055-min-in-max-ex-remove-maximum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-055-min-in-max-ex-remove-maximum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("056-min-ex-max-in-remove-minimum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-056-min-ex-max-in-remove-minimum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("057-min-ex-max-in-remove-maximum", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-value-range-samples--case-057-min-ex-max-in-remove-maximum`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
