/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/number-validation-multiple-of.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-number-validation-multiple-of";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Number Validation/Multiple Of", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-multiple-of-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-multiple-of--case-001-multiple-of-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-multiple-of-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-multiple-of--case-002-multiple-of-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-multiple-of-replaced", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-number-validation-multiple-of--case-003-multiple-of-replaced`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
