/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/object-properties.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-object-properties";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Object Properties", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-add-one-property-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-001-add-one-property-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-remove-one-property-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-002-remove-one-property-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-add-two-properties-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-003-add-two-properties-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-remove-two-properties-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-004-remove-two-properties-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-add-one-property-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-005-add-one-property-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-remove-one-property-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-006-remove-one-property-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-add-two-properties-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-007-add-two-properties-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-remove-two-properties-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-008-remove-two-properties-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-add-one-property-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-009-add-one-property-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-remove-one-property-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-010-remove-one-property-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-add-two-properties-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-011-add-two-properties-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-remove-two-properties-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-012-remove-two-properties-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-add-one-property-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-013-add-one-property-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("014-remove-one-property-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-014-remove-one-property-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("015-add-two-properties-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-015-add-two-properties-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("016-remove-two-properties-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-016-remove-two-properties-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("017-add-one-property-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-017-add-one-property-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("018-remove-one-property-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-018-remove-one-property-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("019-add-two-properties-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-019-add-two-properties-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("020-remove-two-properties-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-020-remove-two-properties-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("021-add-one-property-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-021-add-one-property-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("022-remove-one-property-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-022-remove-one-property-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("023-add-two-properties-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-023-add-two-properties-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("024-remove-two-properties-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-024-remove-two-properties-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("025-one-of-add-object-variant-with-prop-type-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-025-one-of-add-object-variant-with-prop-type-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("026-one-of-remove-object-variant-with-prop-type-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-026-one-of-remove-object-variant-with-prop-type-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("027-one-of-add-object-variant-with-prop-type-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-027-one-of-add-object-variant-with-prop-type-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("028-one-of-remove-object-variant-with-prop-type-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-028-one-of-remove-object-variant-with-prop-type-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("029-one-of-add-object-variant-with-prop-type-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-029-one-of-add-object-variant-with-prop-type-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("030-one-of-remove-object-variant-with-prop-type-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-030-one-of-remove-object-variant-with-prop-type-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("031-one-of-add-object-variant-with-prop-type-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-031-one-of-add-object-variant-with-prop-type-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("032-one-of-remove-object-variant-with-prop-type-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-032-one-of-remove-object-variant-with-prop-type-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("033-one-of-add-object-variant-with-prop-type-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-033-one-of-add-object-variant-with-prop-type-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("034-one-of-remove-object-variant-with-prop-type-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-034-one-of-remove-object-variant-with-prop-type-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("035-one-of-add-object-variant-with-prop-type-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-035-one-of-add-object-variant-with-prop-type-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("036-one-of-remove-object-variant-with-prop-type-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties--case-036-one-of-remove-object-variant-with-prop-type-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
