/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/object-properties-samples.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-object-properties-samples";

async function waitForJsonSchemaNextDiffsViewer() {
  await page.waitForSelector('[data-testid="json-schema-next-diffs-viewer"]', { visible: true });
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Object Properties Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-add-one-property-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-001-add-one-property-string`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-remove-one-property-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-002-remove-one-property-string`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-add-two-properties-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-003-add-two-properties-string`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-remove-two-properties-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-004-remove-two-properties-string`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-add-one-property-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-005-add-one-property-number`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-remove-one-property-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-006-remove-one-property-number`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-add-two-properties-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-007-add-two-properties-number`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-remove-two-properties-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-008-remove-two-properties-number`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-add-one-property-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-009-add-one-property-integer`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-remove-one-property-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-010-remove-one-property-integer`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-add-two-properties-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-011-add-two-properties-integer`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-remove-two-properties-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-012-remove-two-properties-integer`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-add-one-property-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-013-add-one-property-boolean`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("014-remove-one-property-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-014-remove-one-property-boolean`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("015-add-two-properties-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-015-add-two-properties-boolean`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("016-remove-two-properties-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-016-remove-two-properties-boolean`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("017-add-one-property-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-017-add-one-property-array`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("018-remove-one-property-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-018-remove-one-property-array`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("019-add-two-properties-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-019-add-two-properties-array`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("020-remove-two-properties-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-020-remove-two-properties-array`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("021-add-one-property-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-021-add-one-property-object`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("022-remove-one-property-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-022-remove-one-property-object`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("023-add-two-properties-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-023-add-two-properties-object`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("024-remove-two-properties-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-properties-samples--case-024-remove-two-properties-object`);
    await waitForJsonSchemaNextDiffsViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
