/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/object-validations-example.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";
import { waitForJsonSchemaDiffsViewer } from "../service/viewer-waits";

const META_ID = "json-schema-diffs-suite-object-validation-object-validations-example";

describe("JSON Schema Diffs Suite/Object Validation/Object Validations Example", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-example-added-empty-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-001-example-added-empty-object`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-example-added-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-002-example-added-object`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-example-removed-empty-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-003-example-removed-empty-object`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-example-removed-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-004-example-removed-object`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-example-replaced-empty-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-005-example-replaced-empty-to-object`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-example-replaced-object-to-empty", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-006-example-replaced-object-to-empty`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-example-replaced-object-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-validation-object-validations-example--case-007-example-replaced-object-to-object`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
