/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/object-additional-properties.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-object-additional-properties";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Object Additional Properties", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-add-additional-properties-rule1-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-001-add-additional-properties-rule-1-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-remove-additional-properties-rule1-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-002-remove-additional-properties-rule-1-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-add-additional-properties-false-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-003-add-additional-properties-false-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-remove-additional-properties-false-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-004-remove-additional-properties-false-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-change-additional-properties-rule1-to-false-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-005-change-additional-properties-rule-1-to-false-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-change-additional-properties-false-to-rule1-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-006-change-additional-properties-false-to-rule-1-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-add-additional-properties-rule1-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-007-add-additional-properties-rule-1-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-remove-additional-properties-rule1-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-008-remove-additional-properties-rule-1-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-add-additional-properties-false-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-009-add-additional-properties-false-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-remove-additional-properties-false-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-010-remove-additional-properties-false-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-change-additional-properties-rule1-to-false-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-011-change-additional-properties-rule-1-to-false-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-change-additional-properties-false-to-rule1-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-012-change-additional-properties-false-to-rule-1-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-add-additional-properties-rule1-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-013-add-additional-properties-rule-1-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("014-remove-additional-properties-rule1-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-014-remove-additional-properties-rule-1-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("015-add-additional-properties-false-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-015-add-additional-properties-false-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("016-remove-additional-properties-false-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-016-remove-additional-properties-false-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("017-change-additional-properties-rule1-to-false-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-017-change-additional-properties-rule-1-to-false-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("018-change-additional-properties-false-to-rule1-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-018-change-additional-properties-false-to-rule-1-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("019-add-additional-properties-rule1-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-019-add-additional-properties-rule-1-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("020-remove-additional-properties-rule1-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-020-remove-additional-properties-rule-1-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("021-add-additional-properties-false-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-021-add-additional-properties-false-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("022-remove-additional-properties-false-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-022-remove-additional-properties-false-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("023-change-additional-properties-rule1-to-false-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-023-change-additional-properties-rule-1-to-false-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("024-change-additional-properties-false-to-rule1-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-024-change-additional-properties-false-to-rule-1-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("025-add-additional-properties-rule1-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-025-add-additional-properties-rule-1-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("026-remove-additional-properties-rule1-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-026-remove-additional-properties-rule-1-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("027-add-additional-properties-false-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-027-add-additional-properties-false-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("028-remove-additional-properties-false-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-028-remove-additional-properties-false-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("029-change-additional-properties-rule1-to-false-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-029-change-additional-properties-rule-1-to-false-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("030-change-additional-properties-false-to-rule1-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-030-change-additional-properties-false-to-rule-1-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("031-add-additional-properties-rule1-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-031-add-additional-properties-rule-1-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("032-remove-additional-properties-rule1-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-032-remove-additional-properties-rule-1-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("033-add-additional-properties-false-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-033-add-additional-properties-false-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("034-remove-additional-properties-false-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-034-remove-additional-properties-false-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("035-change-additional-properties-rule1-to-false-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-035-change-additional-properties-rule-1-to-false-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("036-change-additional-properties-false-to-rule1-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-036-change-additional-properties-false-to-rule-1-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("037-one-of-variant2-add-additional-properties-rule1-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-037-one-of-variant-2-add-additional-properties-rule-1-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("038-one-of-variant2-remove-additional-properties-rule1-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-038-one-of-variant-2-remove-additional-properties-rule-1-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("039-one-of-variant2-add-additional-properties-false-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-039-one-of-variant-2-add-additional-properties-false-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("040-one-of-variant2-remove-additional-properties-false-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-040-one-of-variant-2-remove-additional-properties-false-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("041-one-of-variant2-change-additional-properties-rule1-to-false-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-041-one-of-variant-2-change-additional-properties-rule-1-to-false-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("042-one-of-variant2-change-additional-properties-false-to-rule1-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-042-one-of-variant-2-change-additional-properties-false-to-rule-1-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("043-one-of-variant2-add-additional-properties-rule1-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-043-one-of-variant-2-add-additional-properties-rule-1-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("044-one-of-variant2-remove-additional-properties-rule1-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-044-one-of-variant-2-remove-additional-properties-rule-1-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("045-one-of-variant2-add-additional-properties-false-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-045-one-of-variant-2-add-additional-properties-false-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("046-one-of-variant2-remove-additional-properties-false-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-046-one-of-variant-2-remove-additional-properties-false-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("047-one-of-variant2-change-additional-properties-rule1-to-false-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-047-one-of-variant-2-change-additional-properties-rule-1-to-false-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("048-one-of-variant2-change-additional-properties-false-to-rule1-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-048-one-of-variant-2-change-additional-properties-false-to-rule-1-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("049-one-of-variant2-add-additional-properties-rule1-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-049-one-of-variant-2-add-additional-properties-rule-1-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("050-one-of-variant2-remove-additional-properties-rule1-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-050-one-of-variant-2-remove-additional-properties-rule-1-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("051-one-of-variant2-add-additional-properties-false-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-051-one-of-variant-2-add-additional-properties-false-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("052-one-of-variant2-remove-additional-properties-false-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-052-one-of-variant-2-remove-additional-properties-false-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("053-one-of-variant2-change-additional-properties-rule1-to-false-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-053-one-of-variant-2-change-additional-properties-rule-1-to-false-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("054-one-of-variant2-change-additional-properties-false-to-rule1-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-054-one-of-variant-2-change-additional-properties-false-to-rule-1-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("055-one-of-variant2-add-additional-properties-rule1-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-055-one-of-variant-2-add-additional-properties-rule-1-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("056-one-of-variant2-remove-additional-properties-rule1-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-056-one-of-variant-2-remove-additional-properties-rule-1-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("057-one-of-variant2-add-additional-properties-false-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-057-one-of-variant-2-add-additional-properties-false-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("058-one-of-variant2-remove-additional-properties-false-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-058-one-of-variant-2-remove-additional-properties-false-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("059-one-of-variant2-change-additional-properties-rule1-to-false-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-059-one-of-variant-2-change-additional-properties-rule-1-to-false-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("060-one-of-variant2-change-additional-properties-false-to-rule1-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-060-one-of-variant-2-change-additional-properties-false-to-rule-1-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("061-one-of-variant2-add-additional-properties-rule1-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-061-one-of-variant-2-add-additional-properties-rule-1-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("062-one-of-variant2-remove-additional-properties-rule1-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-062-one-of-variant-2-remove-additional-properties-rule-1-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("063-one-of-variant2-add-additional-properties-false-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-063-one-of-variant-2-add-additional-properties-false-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("064-one-of-variant2-remove-additional-properties-false-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-064-one-of-variant-2-remove-additional-properties-false-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("065-one-of-variant2-change-additional-properties-rule1-to-false-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-065-one-of-variant-2-change-additional-properties-rule-1-to-false-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("066-one-of-variant2-change-additional-properties-false-to-rule1-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-066-one-of-variant-2-change-additional-properties-false-to-rule-1-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("067-one-of-variant2-add-additional-properties-rule1-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-067-one-of-variant-2-add-additional-properties-rule-1-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("068-one-of-variant2-remove-additional-properties-rule1-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-068-one-of-variant-2-remove-additional-properties-rule-1-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("069-one-of-variant2-add-additional-properties-false-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-069-one-of-variant-2-add-additional-properties-false-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("070-one-of-variant2-remove-additional-properties-false-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-070-one-of-variant-2-remove-additional-properties-false-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("071-one-of-variant2-change-additional-properties-rule1-to-false-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-071-one-of-variant-2-change-additional-properties-rule-1-to-false-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("072-one-of-variant2-change-additional-properties-false-to-rule1-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-object-additional-properties--case-072-one-of-variant-2-change-additional-properties-false-to-rule-1-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
