/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/one-of-object-variant-samples.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-oneof-object-variant-samples";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-testid="json-schema-next-diffs-viewer"]', { visible: true });
  await page.waitForFunction(() => {
    for (const selector of ['[data-name="JsonNode"]', '[data-testid="json-schema-combiner-node-viewer"]']) {
      const element = document.querySelector(selector);
      if (!element) {
        continue;
      }
      const rect = element.getBoundingClientRect();
      if (rect.width > 0 && rect.height > 0) {
        return true;
      }
    }
    return false;
  });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/OneOf Object Variant Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-object-variant-add-one-property-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-001-object-variant-add-one-property-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-object-variant-remove-one-property-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-002-object-variant-remove-one-property-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-object-variant-add-two-properties-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-003-object-variant-add-two-properties-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-object-variant-remove-two-properties-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-004-object-variant-remove-two-properties-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-object-variant-added-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-005-object-variant-added-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-object-variant-removed-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-006-object-variant-removed-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-one-of-prop-added-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-007-one-of-prop-added-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-one-of-prop-removed-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-008-one-of-prop-removed-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-object-variant-add-one-property-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-009-object-variant-add-one-property-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-object-variant-remove-one-property-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-010-object-variant-remove-one-property-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-object-variant-add-two-properties-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-011-object-variant-add-two-properties-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-object-variant-remove-two-properties-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-012-object-variant-remove-two-properties-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-object-variant-added-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-013-object-variant-added-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("014-object-variant-removed-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-014-object-variant-removed-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("015-one-of-prop-added-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-015-one-of-prop-added-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("016-one-of-prop-removed-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-016-one-of-prop-removed-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("017-object-variant-add-one-property-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-017-object-variant-add-one-property-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("018-object-variant-remove-one-property-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-018-object-variant-remove-one-property-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("019-object-variant-add-two-properties-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-019-object-variant-add-two-properties-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("020-object-variant-remove-two-properties-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-020-object-variant-remove-two-properties-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("021-object-variant-added-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-021-object-variant-added-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("022-object-variant-removed-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-022-object-variant-removed-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("023-one-of-prop-added-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-023-one-of-prop-added-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("024-one-of-prop-removed-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-024-one-of-prop-removed-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("025-object-variant-add-one-property-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-025-object-variant-add-one-property-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("026-object-variant-remove-one-property-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-026-object-variant-remove-one-property-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("027-object-variant-add-two-properties-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-027-object-variant-add-two-properties-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("028-object-variant-remove-two-properties-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-028-object-variant-remove-two-properties-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("029-object-variant-added-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-029-object-variant-added-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("030-object-variant-removed-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-030-object-variant-removed-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("031-one-of-prop-added-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-031-one-of-prop-added-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("032-one-of-prop-removed-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-032-one-of-prop-removed-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("033-object-variant-add-one-property-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-033-object-variant-add-one-property-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("034-object-variant-remove-one-property-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-034-object-variant-remove-one-property-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("035-object-variant-add-two-properties-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-035-object-variant-add-two-properties-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("036-object-variant-remove-two-properties-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-036-object-variant-remove-two-properties-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("037-object-variant-added-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-037-object-variant-added-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("038-object-variant-removed-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-038-object-variant-removed-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("039-one-of-prop-added-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-039-one-of-prop-added-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("040-one-of-prop-removed-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-040-one-of-prop-removed-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("041-object-variant-add-one-property-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-041-object-variant-add-one-property-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("042-object-variant-remove-one-property-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-042-object-variant-remove-one-property-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("043-object-variant-add-two-properties-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-043-object-variant-add-two-properties-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("044-object-variant-remove-two-properties-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-044-object-variant-remove-two-properties-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("045-object-variant-added-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-045-object-variant-added-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("046-object-variant-removed-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-046-object-variant-removed-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("047-one-of-prop-added-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-047-one-of-prop-added-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("048-one-of-prop-removed-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-oneof-object-variant-samples--case-048-one-of-prop-removed-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
