/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-property-rename-suite.mjs
 * Edit together with src/stories/json-schema-diffs-suite/property-rename.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";
import { waitForJsonSchemaDiffsViewer } from "../service/viewer-waits";

const META_ID = "json-schema-diffs-suite-property-rename";

describe("JSON Schema Diffs Suite/Property Rename", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("01-renamed-only", async () => {
    story = await storyPage(page, `${META_ID}--case-01-renamed-only`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("02-renamed-and-description-changed", async () => {
    story = await storyPage(page, `${META_ID}--case-02-renamed-and-description-changed`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("03-renamed-and-type-changed", async () => {
    story = await storyPage(page, `${META_ID}--case-03-renamed-and-type-changed`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("04-renamed-and-validation-changed", async () => {
    story = await storyPage(page, `${META_ID}--case-04-renamed-and-validation-changed`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("05-renamed-and-deprecated", async () => {
    story = await storyPage(page, `${META_ID}--case-05-renamed-and-deprecated`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("06-renamed-object-parameter", async () => {
    story = await storyPage(page, `${META_ID}--case-06-renamed-object-parameter`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("07-two-parameters-renamed", async () => {
    story = await storyPage(page, `${META_ID}--case-07-two-parameters-renamed`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("08-renamed-with-query-parameter-added", async () => {
    story = await storyPage(page, `${META_ID}--case-08-renamed-with-query-parameter-added`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("09-query-parameter-renamed-is-removed-and-added", async () => {
    story = await storyPage(page, `${META_ID}--case-09-query-parameter-renamed-is-removed-and-added`);
    await waitForJsonSchemaDiffsViewer(page);
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
