/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/string-validation-enum.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";
import { waitForJsonSchemaDiffsViewer } from "../service/viewer-waits";

const META_ID = "json-schema-diffs-suite-string-validation-string-validation-enum";

describe("JSON Schema Diffs Suite/String Validation/String Validation Enum", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-enum-two-values-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-string-validation-string-validation-enum--case-001-enum-two-values-added`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-enum-two-values-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-string-validation-string-validation-enum--case-002-enum-two-values-removed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-enum-value-appended", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-string-validation-string-validation-enum--case-003-enum-value-appended`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-enum-value-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-string-validation-string-validation-enum--case-004-enum-value-removed`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-enum-two-values-unchanged", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-string-validation-string-validation-enum--case-005-enum-two-values-unchanged`);
    await waitForJsonSchemaDiffsViewer(page, { switchCombinerVariant: true });
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
