/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/type-value-changes.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-type-value-changes-samples";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-name="JsonNode"]', { visible: true });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Type Value Changes Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-string-to-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-001-string-to-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-string-to-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-002-string-to-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-string-to-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-003-string-to-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-string-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-004-string-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-string-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-005-string-to-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-number-to-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-006-number-to-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-number-to-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-007-number-to-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-number-to-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-008-number-to-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-number-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-009-number-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-number-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-010-number-to-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-integer-to-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-011-integer-to-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-integer-to-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-012-integer-to-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-integer-to-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-013-integer-to-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("014-integer-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-014-integer-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("015-integer-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-015-integer-to-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("016-boolean-to-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-016-boolean-to-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("017-boolean-to-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-017-boolean-to-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("018-boolean-to-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-018-boolean-to-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("019-boolean-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-019-boolean-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("020-boolean-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-020-boolean-to-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("021-array-to-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-021-array-to-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("022-array-to-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-022-array-to-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("023-array-to-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-023-array-to-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("024-array-to-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-024-array-to-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("025-array-to-object", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-025-array-to-object`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("026-object-to-string", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-026-object-to-string`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("027-object-to-number", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-027-object-to-number`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("028-object-to-integer", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-028-object-to-integer`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("029-object-to-boolean", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-029-object-to-boolean`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("030-object-to-array", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-value-changes-samples--case-030-object-to-array`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
