/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Edit together with src/stories/json-schema-diffs-suite/type-flags.stories.tsx
 */
import { StoryPage } from "../service/story-page";
import { ViewComponent } from "../service/view-component";
import { storyPage } from "../service/storybook-service";

const META_ID = "json-schema-diffs-suite-type-flags-samples";

async function waitForJsonSchemaDiffViewer() {
  await page.waitForSelector('[data-testid="json-schema-next-diffs-viewer"]', { visible: true });
  await page.waitForFunction(() => {
    for (const selector of ['[data-name="JsonNode"]', '[data-testid="json-schema-combiner-node-viewer"]']) {
      const element = document.querySelector(selector);
      if (!element) {
        continue;
      }
      const rect = element.getBoundingClientRect();
      if (rect.width > 0 && rect.height > 0) {
        return true;
      }
    }
    return false;
  });
  await page.waitForFunction(() => document.readyState === "complete");
  await page.evaluate(() => new Promise<void>((resolve) =>
    requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
  ));
}

describe("JSON Schema Diffs Suite/Type Flags Samples", () => {
  let story: StoryPage;
  let component: ViewComponent;

  beforeEach(async () => {
    await jestPuppeteer.resetPage();
  });

  it("001-read-only-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-001-read-only-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("002-read-only-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-002-read-only-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("003-write-only-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-003-write-only-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("004-write-only-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-004-write-only-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("005-deprecated-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-005-deprecated-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("006-deprecated-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-006-deprecated-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("007-required-added", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-007-required-added`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("008-required-removed", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-008-required-removed`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("009-unchanged-read-only", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-009-unchanged-read-only`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("010-unchanged-write-only", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-010-unchanged-write-only`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("011-unchanged-deprecated", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-011-unchanged-deprecated`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("012-unchanged-required-field", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-012-unchanged-required-field`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });

  it("013-unchanged-required-optional", async () => {
    story = await storyPage(page, `json-schema-diffs-suite-type-flags-samples--case-013-unchanged-required-optional`);
    await waitForJsonSchemaDiffViewer();
    component = await story.viewComponent();
    expect(await component.captureScreenshot()).toMatchImageSnapshot();
  });
});
