/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/array-indexed-items/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_add_one_indexed_item_string: Story;
export declare const Case_002_remove_one_indexed_item_string: Story;
export declare const Case_003_add_two_indexed_items_string: Story;
export declare const Case_004_remove_two_indexed_items_string: Story;
export declare const Case_005_add_one_indexed_item_number: Story;
export declare const Case_006_remove_one_indexed_item_number: Story;
export declare const Case_007_add_two_indexed_items_number: Story;
export declare const Case_008_remove_two_indexed_items_number: Story;
export declare const Case_009_add_one_indexed_item_integer: Story;
export declare const Case_010_remove_one_indexed_item_integer: Story;
export declare const Case_011_add_two_indexed_items_integer: Story;
export declare const Case_012_remove_two_indexed_items_integer: Story;
export declare const Case_013_add_one_indexed_item_boolean: Story;
export declare const Case_014_remove_one_indexed_item_boolean: Story;
export declare const Case_015_add_two_indexed_items_boolean: Story;
export declare const Case_016_remove_two_indexed_items_boolean: Story;
export declare const Case_017_add_one_indexed_item_array: Story;
export declare const Case_018_remove_one_indexed_item_array: Story;
export declare const Case_019_add_two_indexed_items_array: Story;
export declare const Case_020_remove_two_indexed_items_array: Story;
export declare const Case_021_add_one_indexed_item_object: Story;
export declare const Case_022_remove_one_indexed_item_object: Story;
export declare const Case_023_add_two_indexed_items_object: Story;
export declare const Case_024_remove_two_indexed_items_object: Story;
