/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/description-changes/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_description_added: Story;
export declare const Case_002_description_removed: Story;
export declare const Case_003_description_replaced: Story;
export declare const Case_004_description_with_enum_added: Story;
export declare const Case_005_description_with_enum_removed: Story;
export declare const Case_006_description_with_enum_replaced: Story;
export declare const Case_007_unchanged_description_short: Story;
export declare const Case_008_unchanged_description_long: Story;
export declare const Case_009_description_changed_short_line_text_changed: Story;
export declare const Case_010_description_changed_short_lines_text_changed: Story;
export declare const Case_011_description_changed_long_line_text_changed: Story;
export declare const Case_012_description_changed_long_lines_text_changed: Story;
export declare const Case_013_description_changed_short_line_to_short_lines: Story;
export declare const Case_014_description_changed_short_line_to_long_line: Story;
export declare const Case_015_description_changed_short_line_to_long_lines: Story;
export declare const Case_016_description_changed_short_lines_to_short_line: Story;
export declare const Case_017_description_changed_short_lines_to_long_line: Story;
export declare const Case_018_description_changed_short_lines_to_long_lines: Story;
export declare const Case_019_description_changed_long_line_to_short_line: Story;
export declare const Case_020_description_changed_long_line_to_short_lines: Story;
export declare const Case_021_description_changed_long_line_to_long_lines: Story;
export declare const Case_022_description_changed_long_lines_to_short_line: Story;
export declare const Case_023_description_changed_long_lines_to_short_lines: Story;
export declare const Case_024_description_changed_long_lines_to_long_line: Story;
export declare const Case_025_unchanged_description_short_multiline: Story;
export declare const Case_026_unchanged_description_long_multiline: Story;
