/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-validations/example/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_example_added_empty_object: Story;
export declare const Case_002_example_added_object: Story;
export declare const Case_003_example_removed_empty_object: Story;
export declare const Case_004_example_removed_object: Story;
export declare const Case_005_example_replaced_empty_to_object: Story;
export declare const Case_006_example_replaced_object_to_empty: Story;
export declare const Case_007_example_replaced_object_to_object: Story;
