/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-properties/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_add_one_property_string: Story;
export declare const Case_002_remove_one_property_string: Story;
export declare const Case_003_add_two_properties_string: Story;
export declare const Case_004_remove_two_properties_string: Story;
export declare const Case_005_add_one_property_number: Story;
export declare const Case_006_remove_one_property_number: Story;
export declare const Case_007_add_two_properties_number: Story;
export declare const Case_008_remove_two_properties_number: Story;
export declare const Case_009_add_one_property_integer: Story;
export declare const Case_010_remove_one_property_integer: Story;
export declare const Case_011_add_two_properties_integer: Story;
export declare const Case_012_remove_two_properties_integer: Story;
export declare const Case_013_add_one_property_boolean: Story;
export declare const Case_014_remove_one_property_boolean: Story;
export declare const Case_015_add_two_properties_boolean: Story;
export declare const Case_016_remove_two_properties_boolean: Story;
export declare const Case_017_add_one_property_array: Story;
export declare const Case_018_remove_one_property_array: Story;
export declare const Case_019_add_two_properties_array: Story;
export declare const Case_020_remove_two_properties_array: Story;
export declare const Case_021_add_one_property_object: Story;
export declare const Case_022_remove_one_property_object: Story;
export declare const Case_023_add_two_properties_object: Story;
export declare const Case_024_remove_two_properties_object: Story;
export declare const Case_025_one_of_variant2_added_string: Story;
export declare const Case_026_one_of_variant2_removed_string: Story;
export declare const Case_027_one_of_variant2_added_number: Story;
export declare const Case_028_one_of_variant2_removed_number: Story;
export declare const Case_029_one_of_variant2_added_integer: Story;
export declare const Case_030_one_of_variant2_removed_integer: Story;
export declare const Case_031_one_of_variant2_added_boolean: Story;
export declare const Case_032_one_of_variant2_removed_boolean: Story;
export declare const Case_033_one_of_variant2_added_array: Story;
export declare const Case_034_one_of_variant2_removed_array: Story;
export declare const Case_035_one_of_variant2_added_object: Story;
export declare const Case_036_one_of_variant2_removed_object: Story;
