/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-additional-properties/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_add_additional_properties_rule1_string: Story;
export declare const Case_002_remove_additional_properties_rule1_string: Story;
export declare const Case_003_add_additional_properties_false_string: Story;
export declare const Case_004_remove_additional_properties_false_string: Story;
export declare const Case_005_change_additional_properties_rule1_to_false_string: Story;
export declare const Case_006_change_additional_properties_false_to_rule1_string: Story;
export declare const Case_007_add_additional_properties_rule1_number: Story;
export declare const Case_008_remove_additional_properties_rule1_number: Story;
export declare const Case_009_add_additional_properties_false_number: Story;
export declare const Case_010_remove_additional_properties_false_number: Story;
export declare const Case_011_change_additional_properties_rule1_to_false_number: Story;
export declare const Case_012_change_additional_properties_false_to_rule1_number: Story;
export declare const Case_013_add_additional_properties_rule1_integer: Story;
export declare const Case_014_remove_additional_properties_rule1_integer: Story;
export declare const Case_015_add_additional_properties_false_integer: Story;
export declare const Case_016_remove_additional_properties_false_integer: Story;
export declare const Case_017_change_additional_properties_rule1_to_false_integer: Story;
export declare const Case_018_change_additional_properties_false_to_rule1_integer: Story;
export declare const Case_019_add_additional_properties_rule1_boolean: Story;
export declare const Case_020_remove_additional_properties_rule1_boolean: Story;
export declare const Case_021_add_additional_properties_false_boolean: Story;
export declare const Case_022_remove_additional_properties_false_boolean: Story;
export declare const Case_023_change_additional_properties_rule1_to_false_boolean: Story;
export declare const Case_024_change_additional_properties_false_to_rule1_boolean: Story;
export declare const Case_025_add_additional_properties_rule1_array: Story;
export declare const Case_026_remove_additional_properties_rule1_array: Story;
export declare const Case_027_add_additional_properties_false_array: Story;
export declare const Case_028_remove_additional_properties_false_array: Story;
export declare const Case_029_change_additional_properties_rule1_to_false_array: Story;
export declare const Case_030_change_additional_properties_false_to_rule1_array: Story;
export declare const Case_031_add_additional_properties_rule1_object: Story;
export declare const Case_032_remove_additional_properties_rule1_object: Story;
export declare const Case_033_add_additional_properties_false_object: Story;
export declare const Case_034_remove_additional_properties_false_object: Story;
export declare const Case_035_change_additional_properties_rule1_to_false_object: Story;
export declare const Case_036_change_additional_properties_false_to_rule1_object: Story;
export declare const Case_037_one_of_variant2_add_additional_properties_rule1_string: Story;
export declare const Case_038_one_of_variant2_remove_additional_properties_rule1_string: Story;
export declare const Case_039_one_of_variant2_add_additional_properties_false_string: Story;
export declare const Case_040_one_of_variant2_remove_additional_properties_false_string: Story;
export declare const Case_041_one_of_variant2_change_additional_properties_rule1_to_false_string: Story;
export declare const Case_042_one_of_variant2_change_additional_properties_false_to_rule1_string: Story;
export declare const Case_043_one_of_variant2_add_additional_properties_rule1_number: Story;
export declare const Case_044_one_of_variant2_remove_additional_properties_rule1_number: Story;
export declare const Case_045_one_of_variant2_add_additional_properties_false_number: Story;
export declare const Case_046_one_of_variant2_remove_additional_properties_false_number: Story;
export declare const Case_047_one_of_variant2_change_additional_properties_rule1_to_false_number: Story;
export declare const Case_048_one_of_variant2_change_additional_properties_false_to_rule1_number: Story;
export declare const Case_049_one_of_variant2_add_additional_properties_rule1_integer: Story;
export declare const Case_050_one_of_variant2_remove_additional_properties_rule1_integer: Story;
export declare const Case_051_one_of_variant2_add_additional_properties_false_integer: Story;
export declare const Case_052_one_of_variant2_remove_additional_properties_false_integer: Story;
export declare const Case_053_one_of_variant2_change_additional_properties_rule1_to_false_integer: Story;
export declare const Case_054_one_of_variant2_change_additional_properties_false_to_rule1_integer: Story;
export declare const Case_055_one_of_variant2_add_additional_properties_rule1_boolean: Story;
export declare const Case_056_one_of_variant2_remove_additional_properties_rule1_boolean: Story;
export declare const Case_057_one_of_variant2_add_additional_properties_false_boolean: Story;
export declare const Case_058_one_of_variant2_remove_additional_properties_false_boolean: Story;
export declare const Case_059_one_of_variant2_change_additional_properties_rule1_to_false_boolean: Story;
export declare const Case_060_one_of_variant2_change_additional_properties_false_to_rule1_boolean: Story;
export declare const Case_061_one_of_variant2_add_additional_properties_rule1_array: Story;
export declare const Case_062_one_of_variant2_remove_additional_properties_rule1_array: Story;
export declare const Case_063_one_of_variant2_add_additional_properties_false_array: Story;
export declare const Case_064_one_of_variant2_remove_additional_properties_false_array: Story;
export declare const Case_065_one_of_variant2_change_additional_properties_rule1_to_false_array: Story;
export declare const Case_066_one_of_variant2_change_additional_properties_false_to_rule1_array: Story;
export declare const Case_067_one_of_variant2_add_additional_properties_rule1_object: Story;
export declare const Case_068_one_of_variant2_remove_additional_properties_rule1_object: Story;
export declare const Case_069_one_of_variant2_add_additional_properties_false_object: Story;
export declare const Case_070_one_of_variant2_remove_additional_properties_false_object: Story;
export declare const Case_071_one_of_variant2_change_additional_properties_rule1_to_false_object: Story;
export declare const Case_072_one_of_variant2_change_additional_properties_false_to_rule1_object: Story;
