/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/one-of-object-variant/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_object_variant_add_one_property_string: Story;
export declare const Case_002_object_variant_remove_one_property_string: Story;
export declare const Case_003_object_variant_add_two_properties_string: Story;
export declare const Case_004_object_variant_remove_two_properties_string: Story;
export declare const Case_005_object_variant_added_string: Story;
export declare const Case_006_object_variant_removed_string: Story;
export declare const Case_007_one_of_prop_added_string: Story;
export declare const Case_008_one_of_prop_removed_string: Story;
export declare const Case_009_object_variant_add_one_property_number: Story;
export declare const Case_010_object_variant_remove_one_property_number: Story;
export declare const Case_011_object_variant_add_two_properties_number: Story;
export declare const Case_012_object_variant_remove_two_properties_number: Story;
export declare const Case_013_object_variant_added_number: Story;
export declare const Case_014_object_variant_removed_number: Story;
export declare const Case_015_one_of_prop_added_number: Story;
export declare const Case_016_one_of_prop_removed_number: Story;
export declare const Case_017_object_variant_add_one_property_integer: Story;
export declare const Case_018_object_variant_remove_one_property_integer: Story;
export declare const Case_019_object_variant_add_two_properties_integer: Story;
export declare const Case_020_object_variant_remove_two_properties_integer: Story;
export declare const Case_021_object_variant_added_integer: Story;
export declare const Case_022_object_variant_removed_integer: Story;
export declare const Case_023_one_of_prop_added_integer: Story;
export declare const Case_024_one_of_prop_removed_integer: Story;
export declare const Case_025_object_variant_add_one_property_boolean: Story;
export declare const Case_026_object_variant_remove_one_property_boolean: Story;
export declare const Case_027_object_variant_add_two_properties_boolean: Story;
export declare const Case_028_object_variant_remove_two_properties_boolean: Story;
export declare const Case_029_object_variant_added_boolean: Story;
export declare const Case_030_object_variant_removed_boolean: Story;
export declare const Case_031_one_of_prop_added_boolean: Story;
export declare const Case_032_one_of_prop_removed_boolean: Story;
export declare const Case_033_object_variant_add_one_property_array: Story;
export declare const Case_034_object_variant_remove_one_property_array: Story;
export declare const Case_035_object_variant_add_two_properties_array: Story;
export declare const Case_036_object_variant_remove_two_properties_array: Story;
export declare const Case_037_object_variant_added_array: Story;
export declare const Case_038_object_variant_removed_array: Story;
export declare const Case_039_one_of_prop_added_array: Story;
export declare const Case_040_one_of_prop_removed_array: Story;
export declare const Case_041_object_variant_add_one_property_object: Story;
export declare const Case_042_object_variant_remove_one_property_object: Story;
export declare const Case_043_object_variant_add_two_properties_object: Story;
export declare const Case_044_object_variant_remove_two_properties_object: Story;
export declare const Case_045_object_variant_added_object: Story;
export declare const Case_046_object_variant_removed_object: Story;
export declare const Case_047_one_of_prop_added_object: Story;
export declare const Case_048_one_of_prop_removed_object: Story;
