/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/string-validation/value-length/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_min_length_added: Story;
export declare const Case_002_min_length_removed: Story;
export declare const Case_003_min_length_replaced: Story;
export declare const Case_004_max_length_added: Story;
export declare const Case_005_max_length_removed: Story;
export declare const Case_006_max_length_replaced: Story;
export declare const Case_007_min_max_length_added: Story;
export declare const Case_008_min_max_length_removed: Story;
export declare const Case_009_min_length_added_max_length_removed: Story;
export declare const Case_010_min_length_removed_max_length_added: Story;
export declare const Case_011_both_lengths_replace_min: Story;
export declare const Case_012_both_lengths_replace_max: Story;
export declare const Case_013_both_lengths_replaced: Story;
export declare const Case_014_unchanged_min_length: Story;
export declare const Case_015_unchanged_max_length: Story;
export declare const Case_016_unchanged_min_max_length: Story;
