import {
  JSON_SCHEMA_PROPERTY_ENUM,
  JSON_SCHEMA_PROPERTY_EXCLUSIVE_MAXIMUM,
  JSON_SCHEMA_PROPERTY_EXCLUSIVE_MINIMUM,
  JSON_SCHEMA_PROPERTY_MAXIMUM,
  JSON_SCHEMA_PROPERTY_MAX_ITEMS,
  JSON_SCHEMA_PROPERTY_MAX_LENGTH,
  JSON_SCHEMA_PROPERTY_MAX_PROPERTIES,
  JSON_SCHEMA_PROPERTY_MINIMUM,
  JSON_SCHEMA_PROPERTY_MIN_ITEMS,
  JSON_SCHEMA_PROPERTY_MIN_LENGTH,
  JSON_SCHEMA_PROPERTY_MIN_PROPERTIES,
  JSON_SCHEMA_PROPERTY_MULTIPLE_OF,
  JSON_SCHEMA_PROPERTY_PATTERN,
  JSON_SCHEMA_PROPERTY_UNIQUE_ITEMS,
} from "@netcracker/qubership-apihub-api-unifier"

export const JsonSchemaValidationKeys = {
  ENUM: JSON_SCHEMA_PROPERTY_ENUM,
  MIN_LENGTH: JSON_SCHEMA_PROPERTY_MIN_LENGTH,
  MAX_LENGTH: JSON_SCHEMA_PROPERTY_MAX_LENGTH,
  PATTERN: JSON_SCHEMA_PROPERTY_PATTERN,
  MINIMUM: JSON_SCHEMA_PROPERTY_MINIMUM,
  MAXIMUM: JSON_SCHEMA_PROPERTY_MAXIMUM,
  EXCLUSIVE_MINIMUM: JSON_SCHEMA_PROPERTY_EXCLUSIVE_MINIMUM,
  EXCLUSIVE_MAXIMUM: JSON_SCHEMA_PROPERTY_EXCLUSIVE_MAXIMUM,
  MULTIPLE_OF: JSON_SCHEMA_PROPERTY_MULTIPLE_OF,
  MIN_PROPERTIES: JSON_SCHEMA_PROPERTY_MIN_PROPERTIES,
  MAX_PROPERTIES: JSON_SCHEMA_PROPERTY_MAX_PROPERTIES,
  UNIQUE_ITEMS: JSON_SCHEMA_PROPERTY_UNIQUE_ITEMS,
  MIN_ITEMS: JSON_SCHEMA_PROPERTY_MIN_ITEMS,
  MAX_ITEMS: JSON_SCHEMA_PROPERTY_MAX_ITEMS,
} as const

export type JsonSchemaValidationKey = typeof JsonSchemaValidationKeys[keyof typeof JsonSchemaValidationKeys]

export const JsonSchemaValidationKeysList: JsonSchemaValidationKey[] = Object.values(JsonSchemaValidationKeys)
