/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/extended/combiners-one-level/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_append_variant_string: Story;
export declare const Case_002_append_variant_object: Story;
export declare const Case_003_append_variant_array: Story;
export declare const Case_004_remove_variant_string: Story;
export declare const Case_005_remove_variant_object: Story;
export declare const Case_006_remove_variant_array: Story;
export declare const Case_007_change_variant_string: Story;
export declare const Case_008_change_variant_object: Story;
export declare const Case_009_change_variant_array: Story;
export declare const Case_010_append_variant_nested_combiner: Story;
export declare const Case_011_remove_variant_nested_combiner: Story;
