/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-additional-properties/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_add_additional_properties_false: Story;
export declare const Case_002_remove_additional_properties_false: Story;
export declare const Case_003_add_additional_properties_type_string: Story;
export declare const Case_004_remove_additional_properties_type_string: Story;
export declare const Case_005_change_additional_properties_string_to_false: Story;
export declare const Case_006_change_additional_properties_false_to_string: Story;
export declare const Case_007_add_additional_properties_type_number: Story;
export declare const Case_008_remove_additional_properties_type_number: Story;
export declare const Case_009_change_additional_properties_number_to_false: Story;
export declare const Case_010_change_additional_properties_false_to_number: Story;
export declare const Case_011_add_additional_properties_type_integer: Story;
export declare const Case_012_remove_additional_properties_type_integer: Story;
export declare const Case_013_change_additional_properties_integer_to_false: Story;
export declare const Case_014_change_additional_properties_false_to_integer: Story;
export declare const Case_015_add_additional_properties_type_boolean: Story;
export declare const Case_016_remove_additional_properties_type_boolean: Story;
export declare const Case_017_change_additional_properties_boolean_to_false: Story;
export declare const Case_018_change_additional_properties_false_to_boolean: Story;
export declare const Case_019_add_additional_properties_type_array: Story;
export declare const Case_020_remove_additional_properties_type_array: Story;
export declare const Case_021_change_additional_properties_array_to_false: Story;
export declare const Case_022_change_additional_properties_false_to_array: Story;
export declare const Case_023_add_additional_properties_type_object: Story;
export declare const Case_024_remove_additional_properties_type_object: Story;
export declare const Case_025_change_additional_properties_object_to_false: Story;
export declare const Case_026_change_additional_properties_false_to_object: Story;
export declare const Case_027_one_of_object_variant_add_additional_properties_false: Story;
export declare const Case_028_one_of_object_variant_remove_additional_properties_false: Story;
export declare const Case_029_one_of_object_variant_add_additional_properties_type_string: Story;
export declare const Case_030_one_of_object_variant_remove_additional_properties_type_string: Story;
export declare const Case_031_one_of_object_variant_change_additional_properties_string_to_false: Story;
export declare const Case_032_one_of_object_variant_change_additional_properties_false_to_string: Story;
export declare const Case_033_one_of_object_variant_add_additional_properties_type_number: Story;
export declare const Case_034_one_of_object_variant_remove_additional_properties_type_number: Story;
export declare const Case_035_one_of_object_variant_change_additional_properties_number_to_false: Story;
export declare const Case_036_one_of_object_variant_change_additional_properties_false_to_number: Story;
export declare const Case_037_one_of_object_variant_add_additional_properties_type_integer: Story;
export declare const Case_038_one_of_object_variant_remove_additional_properties_type_integer: Story;
export declare const Case_039_one_of_object_variant_change_additional_properties_integer_to_false: Story;
export declare const Case_040_one_of_object_variant_change_additional_properties_false_to_integer: Story;
export declare const Case_041_one_of_object_variant_add_additional_properties_type_boolean: Story;
export declare const Case_042_one_of_object_variant_remove_additional_properties_type_boolean: Story;
export declare const Case_043_one_of_object_variant_change_additional_properties_boolean_to_false: Story;
export declare const Case_044_one_of_object_variant_change_additional_properties_false_to_boolean: Story;
export declare const Case_045_one_of_object_variant_add_additional_properties_type_array: Story;
export declare const Case_046_one_of_object_variant_remove_additional_properties_type_array: Story;
export declare const Case_047_one_of_object_variant_change_additional_properties_array_to_false: Story;
export declare const Case_048_one_of_object_variant_change_additional_properties_false_to_array: Story;
export declare const Case_049_one_of_object_variant_add_additional_properties_type_object: Story;
export declare const Case_050_one_of_object_variant_remove_additional_properties_type_object: Story;
export declare const Case_051_one_of_object_variant_change_additional_properties_object_to_false: Story;
export declare const Case_052_one_of_object_variant_change_additional_properties_false_to_object: Story;
