/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-validations/examples/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_examples_added_empty_object: Story;
export declare const Case_002_examples_added_object: Story;
export declare const Case_003_examples_removed_empty_object: Story;
export declare const Case_004_examples_removed_object: Story;
export declare const Case_005_examples_replaced_empty_to_object: Story;
export declare const Case_006_examples_replaced_object_to_empty: Story;
export declare const Case_007_examples_replaced_object_to_object: Story;
export declare const Case_008_examples_two_added_both_empty: Story;
export declare const Case_009_examples_two_added_empty_and_object: Story;
export declare const Case_010_examples_two_added_both_objects: Story;
export declare const Case_011_examples_two_removed_both_empty: Story;
export declare const Case_012_examples_two_removed_empty_and_object: Story;
export declare const Case_013_examples_two_removed_both_objects: Story;
export declare const Case_014_examples_append_empty_to_empty: Story;
export declare const Case_015_examples_append_object_to_empty: Story;
export declare const Case_016_examples_append_object_to_object: Story;
export declare const Case_017_examples_remove_empty_keep_object: Story;
export declare const Case_018_examples_remove_object_keep_empty: Story;
export declare const Case_019_examples_remove_first_of_two_empty: Story;
export declare const Case_020_examples_remove_first_of_two_objects: Story;
export declare const Case_021_examples_replace_empty_with_object: Story;
export declare const Case_022_examples_replace_object_with_empty: Story;
export declare const Case_023_examples_replace_object_with_object: Story;
