/**
 * Programmatic combiner (oneOf) diff stories.
 * See src/stories/json-schema-diffs-suite/combiner-diff-case-definitions.ts and ../../../samples/combiners-cases.md.
 * Regenerate: node --experimental-strip-types bin/generate-combiner-diffs-suite-stories.mjs
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_string_add_option_number: Story;
export declare const Case_002_string_remove_option_number: Story;
export declare const Case_003_string_add_option_integer: Story;
export declare const Case_004_string_remove_option_integer: Story;
export declare const Case_005_string_add_option_boolean: Story;
export declare const Case_006_string_remove_option_boolean: Story;
export declare const Case_007_string_add_option_array: Story;
export declare const Case_008_string_remove_option_array: Story;
export declare const Case_009_string_add_option_object: Story;
export declare const Case_010_string_remove_option_object: Story;
export declare const Case_011_number_add_option_string: Story;
export declare const Case_012_number_remove_option_string: Story;
export declare const Case_013_number_add_option_integer: Story;
export declare const Case_014_number_remove_option_integer: Story;
export declare const Case_015_number_add_option_boolean: Story;
export declare const Case_016_number_remove_option_boolean: Story;
export declare const Case_017_number_add_option_array: Story;
export declare const Case_018_number_remove_option_array: Story;
export declare const Case_019_number_add_option_object: Story;
export declare const Case_020_number_remove_option_object: Story;
export declare const Case_021_integer_add_option_string: Story;
export declare const Case_022_integer_remove_option_string: Story;
export declare const Case_023_integer_add_option_number: Story;
export declare const Case_024_integer_remove_option_number: Story;
export declare const Case_025_integer_add_option_boolean: Story;
export declare const Case_026_integer_remove_option_boolean: Story;
export declare const Case_027_integer_add_option_array: Story;
export declare const Case_028_integer_remove_option_array: Story;
export declare const Case_029_integer_add_option_object: Story;
export declare const Case_030_integer_remove_option_object: Story;
export declare const Case_031_boolean_add_option_string: Story;
export declare const Case_032_boolean_remove_option_string: Story;
export declare const Case_033_boolean_add_option_number: Story;
export declare const Case_034_boolean_remove_option_number: Story;
export declare const Case_035_boolean_add_option_integer: Story;
export declare const Case_036_boolean_remove_option_integer: Story;
export declare const Case_037_boolean_add_option_array: Story;
export declare const Case_038_boolean_remove_option_array: Story;
export declare const Case_039_boolean_add_option_object: Story;
export declare const Case_040_boolean_remove_option_object: Story;
export declare const Case_041_array_add_option_string: Story;
export declare const Case_042_array_remove_option_string: Story;
export declare const Case_043_array_add_option_number: Story;
export declare const Case_044_array_remove_option_number: Story;
export declare const Case_045_array_add_option_integer: Story;
export declare const Case_046_array_remove_option_integer: Story;
export declare const Case_047_array_add_option_boolean: Story;
export declare const Case_048_array_remove_option_boolean: Story;
export declare const Case_049_array_add_option_object: Story;
export declare const Case_050_array_remove_option_object: Story;
export declare const Case_051_object_add_option_string: Story;
export declare const Case_052_object_remove_option_string: Story;
export declare const Case_053_object_add_option_number: Story;
export declare const Case_054_object_remove_option_number: Story;
export declare const Case_055_object_add_option_integer: Story;
export declare const Case_056_object_remove_option_integer: Story;
export declare const Case_057_object_add_option_boolean: Story;
export declare const Case_058_object_remove_option_boolean: Story;
export declare const Case_059_object_add_option_array: Story;
export declare const Case_060_object_remove_option_array: Story;
export declare const Case_061_all_types_string_title_added: Story;
export declare const Case_062_all_types_string_title_removed: Story;
export declare const Case_063_all_types_string_title_replaced: Story;
export declare const Case_064_all_types_string_format_added: Story;
export declare const Case_065_all_types_string_format_removed: Story;
export declare const Case_066_all_types_string_format_replaced: Story;
export declare const Case_067_all_types_string_to_number: Story;
export declare const Case_068_all_types_string_to_integer: Story;
export declare const Case_069_all_types_string_to_boolean: Story;
export declare const Case_070_all_types_string_to_array: Story;
export declare const Case_071_all_types_string_to_object: Story;
export declare const Case_072_all_types_number_title_added: Story;
export declare const Case_073_all_types_number_title_removed: Story;
export declare const Case_074_all_types_number_title_replaced: Story;
export declare const Case_075_all_types_number_format_added: Story;
export declare const Case_076_all_types_number_format_removed: Story;
export declare const Case_077_all_types_number_format_replaced: Story;
export declare const Case_078_all_types_number_to_string: Story;
export declare const Case_079_all_types_number_to_integer: Story;
export declare const Case_080_all_types_number_to_boolean: Story;
export declare const Case_081_all_types_number_to_array: Story;
export declare const Case_082_all_types_number_to_object: Story;
export declare const Case_083_all_types_integer_title_added: Story;
export declare const Case_084_all_types_integer_title_removed: Story;
export declare const Case_085_all_types_integer_title_replaced: Story;
export declare const Case_086_all_types_integer_format_added: Story;
export declare const Case_087_all_types_integer_format_removed: Story;
export declare const Case_088_all_types_integer_format_replaced: Story;
export declare const Case_089_all_types_integer_to_string: Story;
export declare const Case_090_all_types_integer_to_number: Story;
export declare const Case_091_all_types_integer_to_boolean: Story;
export declare const Case_092_all_types_integer_to_array: Story;
export declare const Case_093_all_types_integer_to_object: Story;
export declare const Case_094_all_types_boolean_title_added: Story;
export declare const Case_095_all_types_boolean_title_removed: Story;
export declare const Case_096_all_types_boolean_title_replaced: Story;
export declare const Case_097_all_types_boolean_format_added: Story;
export declare const Case_098_all_types_boolean_format_removed: Story;
export declare const Case_099_all_types_boolean_format_replaced: Story;
export declare const Case_100_all_types_boolean_to_string: Story;
export declare const Case_101_all_types_boolean_to_number: Story;
export declare const Case_102_all_types_boolean_to_integer: Story;
export declare const Case_103_all_types_boolean_to_array: Story;
export declare const Case_104_all_types_boolean_to_object: Story;
export declare const Case_105_all_types_array_title_added: Story;
export declare const Case_106_all_types_array_title_removed: Story;
export declare const Case_107_all_types_array_title_replaced: Story;
export declare const Case_108_all_types_array_format_added: Story;
export declare const Case_109_all_types_array_format_removed: Story;
export declare const Case_110_all_types_array_format_replaced: Story;
export declare const Case_111_all_types_array_to_string: Story;
export declare const Case_112_all_types_array_to_number: Story;
export declare const Case_113_all_types_array_to_integer: Story;
export declare const Case_114_all_types_array_to_boolean: Story;
export declare const Case_115_all_types_array_to_object: Story;
export declare const Case_116_all_types_object_title_added: Story;
export declare const Case_117_all_types_object_title_removed: Story;
export declare const Case_118_all_types_object_title_replaced: Story;
export declare const Case_119_all_types_object_format_added: Story;
export declare const Case_120_all_types_object_format_removed: Story;
export declare const Case_121_all_types_object_format_replaced: Story;
export declare const Case_122_all_types_object_to_string: Story;
export declare const Case_123_all_types_object_to_number: Story;
export declare const Case_124_all_types_object_to_integer: Story;
export declare const Case_125_all_types_object_to_boolean: Story;
export declare const Case_126_all_types_object_to_array: Story;
export declare const Case_127_add_option_number_wrapped_in_one_of: Story;
export declare const Case_128_remove_option_number_wrapped_in_one_of: Story;
export declare const Case_129_add_option_number_wrapped_in_any_of: Story;
export declare const Case_130_remove_option_number_wrapped_in_any_of: Story;
export declare const Case_131_add_option_number_wrapped_in_all_of: Story;
export declare const Case_132_remove_option_number_wrapped_in_all_of: Story;
export declare const Case_133_nested_one_of_string_title_added: Story;
export declare const Case_134_nested_one_of_string_title_removed: Story;
export declare const Case_135_nested_one_of_string_title_replaced: Story;
export declare const Case_136_nested_one_of_string_format_added: Story;
export declare const Case_137_nested_one_of_string_format_removed: Story;
export declare const Case_138_nested_one_of_string_type_changed: Story;
export declare const Case_139_nested_any_of_string_title_added: Story;
export declare const Case_140_nested_any_of_string_title_removed: Story;
export declare const Case_141_nested_any_of_string_title_replaced: Story;
export declare const Case_142_nested_any_of_string_format_added: Story;
export declare const Case_143_nested_any_of_string_format_removed: Story;
export declare const Case_144_nested_any_of_string_type_changed: Story;
export declare const Case_145_nested_all_of_string_title_added: Story;
export declare const Case_146_nested_all_of_string_title_removed: Story;
export declare const Case_147_nested_all_of_string_title_replaced: Story;
export declare const Case_148_nested_all_of_string_format_added: Story;
export declare const Case_149_nested_all_of_string_format_removed: Story;
export declare const Case_150_nested_all_of_string_type_changed: Story;
export declare const Case_151_nested_one_of_nested_one_of_string_title_added: Story;
export declare const Case_152_nested_one_of_nested_one_of_string_title_removed: Story;
export declare const Case_153_nested_one_of_nested_one_of_string_title_replaced: Story;
export declare const Case_154_nested_one_of_nested_any_of_string_title_added: Story;
export declare const Case_155_nested_one_of_nested_any_of_string_title_removed: Story;
export declare const Case_156_nested_one_of_nested_any_of_string_title_replaced: Story;
export declare const Case_157_nested_one_of_nested_all_of_string_title_added: Story;
export declare const Case_158_nested_one_of_nested_all_of_string_title_removed: Story;
export declare const Case_159_nested_one_of_nested_all_of_string_title_replaced: Story;
export declare const Case_160_nested_any_of_nested_one_of_string_title_added: Story;
export declare const Case_161_nested_any_of_nested_one_of_string_title_removed: Story;
export declare const Case_162_nested_any_of_nested_one_of_string_title_replaced: Story;
export declare const Case_163_nested_any_of_nested_any_of_string_title_added: Story;
export declare const Case_164_nested_any_of_nested_any_of_string_title_removed: Story;
export declare const Case_165_nested_any_of_nested_any_of_string_title_replaced: Story;
export declare const Case_166_nested_any_of_nested_all_of_string_title_added: Story;
export declare const Case_167_nested_any_of_nested_all_of_string_title_removed: Story;
export declare const Case_168_nested_any_of_nested_all_of_string_title_replaced: Story;
export declare const Case_169_nested_all_of_nested_one_of_string_title_added: Story;
export declare const Case_170_nested_all_of_nested_one_of_string_title_removed: Story;
export declare const Case_171_nested_all_of_nested_one_of_string_title_replaced: Story;
export declare const Case_172_nested_all_of_nested_any_of_string_title_added: Story;
export declare const Case_173_nested_all_of_nested_any_of_string_title_removed: Story;
export declare const Case_174_nested_all_of_nested_any_of_string_title_replaced: Story;
export declare const Case_175_nested_all_of_nested_all_of_string_title_added: Story;
export declare const Case_176_nested_all_of_nested_all_of_string_title_removed: Story;
export declare const Case_177_nested_all_of_nested_all_of_string_title_replaced: Story;
