/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/one-of-array-variant/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_array_variant_add_one_indexed_item_string: Story;
export declare const Case_002_array_variant_remove_one_indexed_item_string: Story;
export declare const Case_003_array_variant_add_two_indexed_items_string: Story;
export declare const Case_004_array_variant_remove_two_indexed_items_string: Story;
export declare const Case_005_array_variant_added_string: Story;
export declare const Case_006_array_variant_removed_string: Story;
export declare const Case_007_one_of_prop_added_string: Story;
export declare const Case_008_one_of_prop_removed_string: Story;
export declare const Case_009_array_variant_add_one_indexed_item_number: Story;
export declare const Case_010_array_variant_remove_one_indexed_item_number: Story;
export declare const Case_011_array_variant_add_two_indexed_items_number: Story;
export declare const Case_012_array_variant_remove_two_indexed_items_number: Story;
export declare const Case_013_array_variant_added_number: Story;
export declare const Case_014_array_variant_removed_number: Story;
export declare const Case_015_one_of_prop_added_number: Story;
export declare const Case_016_one_of_prop_removed_number: Story;
export declare const Case_017_array_variant_add_one_indexed_item_integer: Story;
export declare const Case_018_array_variant_remove_one_indexed_item_integer: Story;
export declare const Case_019_array_variant_add_two_indexed_items_integer: Story;
export declare const Case_020_array_variant_remove_two_indexed_items_integer: Story;
export declare const Case_021_array_variant_added_integer: Story;
export declare const Case_022_array_variant_removed_integer: Story;
export declare const Case_023_one_of_prop_added_integer: Story;
export declare const Case_024_one_of_prop_removed_integer: Story;
export declare const Case_025_array_variant_add_one_indexed_item_boolean: Story;
export declare const Case_026_array_variant_remove_one_indexed_item_boolean: Story;
export declare const Case_027_array_variant_add_two_indexed_items_boolean: Story;
export declare const Case_028_array_variant_remove_two_indexed_items_boolean: Story;
export declare const Case_029_array_variant_added_boolean: Story;
export declare const Case_030_array_variant_removed_boolean: Story;
export declare const Case_031_one_of_prop_added_boolean: Story;
export declare const Case_032_one_of_prop_removed_boolean: Story;
export declare const Case_033_array_variant_add_one_indexed_item_array: Story;
export declare const Case_034_array_variant_remove_one_indexed_item_array: Story;
export declare const Case_035_array_variant_add_two_indexed_items_array: Story;
export declare const Case_036_array_variant_remove_two_indexed_items_array: Story;
export declare const Case_037_array_variant_added_array: Story;
export declare const Case_038_array_variant_removed_array: Story;
export declare const Case_039_one_of_prop_added_array: Story;
export declare const Case_040_one_of_prop_removed_array: Story;
export declare const Case_041_array_variant_add_one_indexed_item_object: Story;
export declare const Case_042_array_variant_remove_one_indexed_item_object: Story;
export declare const Case_043_array_variant_add_two_indexed_items_object: Story;
export declare const Case_044_array_variant_remove_two_indexed_items_object: Story;
export declare const Case_045_array_variant_added_object: Story;
export declare const Case_046_array_variant_removed_object: Story;
export declare const Case_047_one_of_prop_added_object: Story;
export declare const Case_048_one_of_prop_removed_object: Story;
