/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/type-flags/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_read_only_added: Story;
export declare const Case_002_read_only_removed: Story;
export declare const Case_003_write_only_added: Story;
export declare const Case_004_write_only_removed: Story;
export declare const Case_005_deprecated_added: Story;
export declare const Case_006_deprecated_removed: Story;
export declare const Case_007_required_added: Story;
export declare const Case_008_required_removed: Story;
