/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/type-annotations-changes/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, }: import("./json-schema-diffs-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_001_title_added: Story;
export declare const Case_002_title_removed: Story;
export declare const Case_003_title_replaced: Story;
export declare const Case_004_format_added: Story;
export declare const Case_005_format_removed: Story;
export declare const Case_006_format_replaced: Story;
export declare const Case_007_title_added_format_added: Story;
export declare const Case_008_title_added_format_removed: Story;
export declare const Case_009_title_added_format_replaced: Story;
export declare const Case_010_title_removed_format_added: Story;
export declare const Case_011_title_removed_format_removed: Story;
export declare const Case_012_title_removed_format_replaced: Story;
export declare const Case_013_title_replaced_format_added: Story;
export declare const Case_014_title_replaced_format_removed: Story;
export declare const Case_015_title_replaced_format_replaced: Story;
