import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ caseId }: {
        caseId: string;
    }) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_1_1_channel_title_changed: Story;
export declare const Case_1_2_channel_title_removed: Story;
export declare const Case_1_3_channel_title_added: Story;
export declare const Case_2_1_channel_description_changed: Story;
export declare const Case_2_2_channel_description_removed: Story;
export declare const Case_2_3_channel_description_added: Story;
export declare const Case_2_4_channel_summary_changed: Story;
export declare const Case_2_5_channel_summary_removed: Story;
export declare const Case_2_6_channel_description_moved_to_summary: Story;
export declare const Case_2_7_channel_summary_moved_to_description: Story;
export declare const Case_3_1_channel_bindings_add_amqp: Story;
export declare const Case_3_2_channel_bindings_remove_kafka: Story;
export declare const Case_3_3_channel_bindings_add_kafka: Story;
export declare const Case_3_4_channel_bindings_remove_kafka: Story;
export declare const Case_4_1_channel_bindings_kafka_bindingVersion_changed: Story;
export declare const Case_4_2_channel_bindings_kafka_bindingVersion_removed: Story;
export declare const Case_4_3_channel_bindings_kafka_bindingVersion_added: Story;
export declare const Case_5_1_channel_bindings_kafka_internal_jso_changes: Story;
export declare const Case_6_1_channel_x_second_added: Story;
export declare const Case_6_2_channel_x_second_removed: Story;
export declare const Case_6_3_channel_x_second_changed: Story;
export declare const Case_6_4_channel_x_first_and_x_second_added: Story;
export declare const Case_6_5_channel_x_first_and_x_second_removed: Story;
export declare const Case_7_1_channel_parameters_added: Story;
export declare const Case_7_2_channel_parameters_removed: Story;
export declare const Case_7_3_channel_parameters_firstParam_removed: Story;
export declare const Case_7_4_channel_parameters_secondParam_added: Story;
export declare const Case_7_5_channel_parameters_key_rename: Story;
export declare const Case_7_8_channel_servers_added: Story;
export declare const Case_7_9_channel_servers_removed: Story;
export declare const Case_7_10_channel_servers_one_item_added: Story;
export declare const Case_7_11_channel_servers_one_item_removed: Story;
