import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ caseId }: {
        caseId: string;
    }) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_1_1_message_title_changed: Story;
export declare const Case_1_2_message_title_removed: Story;
export declare const Case_1_3_message_title_added: Story;
export declare const Case_2_1_message_description_changed: Story;
export declare const Case_2_2_message_description_removed: Story;
export declare const Case_2_3_message_description_added: Story;
export declare const Case_2_4_message_summary_changed: Story;
export declare const Case_2_5_message_summary_removed: Story;
export declare const Case_2_6_message_description_moved_to_summary: Story;
export declare const Case_2_7_message_summary_moved_to_description: Story;
export declare const Case_3_1_message_bindings_add_amqp: Story;
export declare const Case_3_2_message_bindings_remove_kafka: Story;
export declare const Case_3_3_message_bindings_add_kafka: Story;
export declare const Case_3_4_message_bindings_remove_kafka: Story;
export declare const Case_4_1_message_bindings_kafka_bindingVersion_changed: Story;
export declare const Case_4_2_message_bindings_kafka_bindingVersion_removed: Story;
export declare const Case_4_3_message_bindings_kafka_bindingVersion_added: Story;
export declare const Case_5_1_1_message_bindings_kafka_string_to_number: Story;
export declare const Case_5_1_2_message_bindings_kafka_number_to_string: Story;
export declare const Case_5_1_3_message_bindings_kafka_string_to_boolean: Story;
export declare const Case_5_1_4_message_bindings_kafka_number_to_null: Story;
export declare const Case_5_1_5_message_bindings_kafka_boolean_to_string: Story;
export declare const Case_5_1_6_message_bindings_kafka_null_to_number: Story;
export declare const Case_5_1_7_message_bindings_kafka_string_to_array_primitives: Story;
export declare const Case_5_1_8_message_bindings_kafka_number_to_array_primitives: Story;
export declare const Case_5_1_9_message_bindings_kafka_string_to_array_objects: Story;
export declare const Case_5_1_10_message_bindings_kafka_number_to_array_objects: Story;
export declare const Case_5_1_11_message_bindings_kafka_string_to_array_arrays_primitives: Story;
export declare const Case_5_1_12_message_bindings_kafka_number_to_array_arrays_primitives: Story;
export declare const Case_5_1_13_message_bindings_kafka_boolean_to_null: Story;
export declare const Case_5_1_14_message_bindings_kafka_boolean_to_array_primitives: Story;
export declare const Case_5_1_15_message_bindings_kafka_null_to_array_primitives: Story;
export declare const Case_5_1_16_message_bindings_kafka_boolean_to_object: Story;
export declare const Case_5_1_17_message_bindings_kafka_null_to_object: Story;
export declare const Case_5_1_18_message_bindings_kafka_array_primitives_to_object: Story;
export declare const Case_5_1_19_message_bindings_kafka_array_objects_to_object: Story;
export declare const Case_5_1_20_message_bindings_kafka_array_arrays_primitives_to_object: Story;
export declare const Case_5_1_21_message_bindings_kafka_remove_object_property: Story;
export declare const Case_5_1_22_message_bindings_kafka_add_object_property: Story;
export declare const Case_6_1_message_x_second_added: Story;
export declare const Case_6_2_message_x_second_removed: Story;
export declare const Case_6_3_message_x_second_changed: Story;
export declare const Case_6_4_message_x_first_and_x_second_added: Story;
export declare const Case_6_5_message_x_first_and_x_second_removed: Story;
export declare const Case_7_1_message_headers_object_schema_added: Story;
export declare const Case_7_2_message_headers_object_schema_removed: Story;
export declare const Case_7_3_message_headers_description_changed: Story;
export declare const Case_7_4_message_payload_object_schema_added: Story;
export declare const Case_7_5_message_payload_object_schema_removed: Story;
export declare const Case_7_6_message_payload_description_changed: Story;
