import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ caseId }: {
        caseId: string;
    }) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_1_1_channel_servers_host_protocol_changed: Story;
export declare const Case_1_2_channel_servers_description_set: Story;
export declare const Case_1_3_channel_servers_summary_set: Story;
export declare const Case_2_1_channel_servers0_bindings_add_amqp: Story;
export declare const Case_2_2_channel_servers0_bindings_remove_kafka: Story;
export declare const Case_2_3_channel_servers0_bindings_add_kafka: Story;
export declare const Case_2_4_channel_servers0_bindings_remove_kafka: Story;
export declare const Case_3_1_channel_servers0_bindings_kafka_bindingVersion_changed: Story;
export declare const Case_3_2_channel_servers0_bindings_kafka_bindingVersion_removed: Story;
export declare const Case_3_3_channel_servers0_bindings_kafka_bindingVersion_added: Story;
export declare const Case_4_1_1_channel_servers0_bindings_kafka_string_to_number: Story;
export declare const Case_4_1_2_channel_servers0_bindings_kafka_number_to_string: Story;
export declare const Case_4_1_3_channel_servers0_bindings_kafka_string_to_boolean: Story;
export declare const Case_4_1_4_channel_servers0_bindings_kafka_number_to_null: Story;
export declare const Case_4_1_5_channel_servers0_bindings_kafka_boolean_to_string: Story;
export declare const Case_4_1_6_channel_servers0_bindings_kafka_null_to_number: Story;
export declare const Case_4_1_7_channel_servers0_bindings_kafka_string_to_array_primitives: Story;
export declare const Case_4_1_8_channel_servers0_bindings_kafka_number_to_array_primitives: Story;
export declare const Case_4_1_9_channel_servers0_bindings_kafka_string_to_array_objects: Story;
export declare const Case_4_1_10_channel_servers0_bindings_kafka_number_to_array_objects: Story;
export declare const Case_4_1_11_channel_servers0_bindings_kafka_string_to_array_arrays_primitives: Story;
export declare const Case_4_1_12_channel_servers0_bindings_kafka_number_to_array_arrays_primitives: Story;
export declare const Case_4_1_13_channel_servers0_bindings_kafka_boolean_to_null: Story;
export declare const Case_4_1_14_channel_servers0_bindings_kafka_boolean_to_array_primitives: Story;
export declare const Case_4_1_15_channel_servers0_bindings_kafka_null_to_array_primitives: Story;
export declare const Case_4_1_16_channel_servers0_bindings_kafka_boolean_to_object: Story;
export declare const Case_4_1_17_channel_servers0_bindings_kafka_null_to_object: Story;
export declare const Case_4_1_18_channel_servers0_bindings_kafka_array_primitives_to_object: Story;
export declare const Case_4_1_19_channel_servers0_bindings_kafka_array_objects_to_object: Story;
export declare const Case_4_1_20_channel_servers0_bindings_kafka_array_arrays_primitives_to_object: Story;
export declare const Case_4_1_21_channel_servers0_bindings_kafka_remove_object_property: Story;
export declare const Case_4_1_22_channel_servers0_bindings_kafka_add_object_property: Story;
export declare const Case_5_1_channel_servers_one_item_removed: Story;
export declare const Case_5_2_channel_servers_one_item_added: Story;
