import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ caseId }: {
        caseId: string;
    }) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_1_1_operation_title_changed: Story;
export declare const Case_1_2_operation_title_removed: Story;
export declare const Case_1_3_operation_title_added: Story;
export declare const Case_2_1_operation_description_changed: Story;
export declare const Case_2_2_operation_description_removed: Story;
export declare const Case_2_3_operation_description_added: Story;
export declare const Case_2_4_operation_summary_changed: Story;
export declare const Case_2_5_operation_summary_removed: Story;
export declare const Case_2_6_operation_description_moved_to_summary: Story;
export declare const Case_2_7_operation_summary_moved_to_description: Story;
export declare const Case_3_1_operation_bindings_add_amqp: Story;
export declare const Case_3_2_operation_bindings_remove_kafka: Story;
export declare const Case_3_3_operation_bindings_add_kafka: Story;
export declare const Case_3_4_operation_bindings_remove_kafka: Story;
export declare const Case_4_1_operation_bindings_kafka_bindingVersion_changed: Story;
export declare const Case_4_2_operation_bindings_kafka_bindingVersion_removed: Story;
export declare const Case_4_3_operation_bindings_kafka_bindingVersion_added: Story;
export declare const Case_5_1_1_operation_bindings_kafka_string_to_number: Story;
export declare const Case_5_1_2_operation_bindings_kafka_number_to_string: Story;
export declare const Case_5_1_3_operation_bindings_kafka_string_to_boolean: Story;
export declare const Case_5_1_4_operation_bindings_kafka_number_to_null: Story;
export declare const Case_5_1_5_operation_bindings_kafka_boolean_to_string: Story;
export declare const Case_5_1_6_operation_bindings_kafka_null_to_number: Story;
export declare const Case_5_1_7_operation_bindings_kafka_string_to_array_primitives: Story;
export declare const Case_5_1_8_operation_bindings_kafka_number_to_array_primitives: Story;
export declare const Case_5_1_9_operation_bindings_kafka_string_to_array_objects: Story;
export declare const Case_5_1_10_operation_bindings_kafka_number_to_array_objects: Story;
export declare const Case_5_1_11_operation_bindings_kafka_string_to_array_arrays_primitives: Story;
export declare const Case_5_1_12_operation_bindings_kafka_number_to_array_arrays_primitives: Story;
export declare const Case_5_1_13_operation_bindings_kafka_boolean_to_null: Story;
export declare const Case_5_1_14_operation_bindings_kafka_boolean_to_array_primitives: Story;
export declare const Case_5_1_15_operation_bindings_kafka_null_to_array_primitives: Story;
export declare const Case_5_1_16_operation_bindings_kafka_boolean_to_object: Story;
export declare const Case_5_1_17_operation_bindings_kafka_null_to_object: Story;
export declare const Case_5_1_18_operation_bindings_kafka_array_primitives_to_object: Story;
export declare const Case_5_1_19_operation_bindings_kafka_array_objects_to_object: Story;
export declare const Case_5_1_20_operation_bindings_kafka_array_arrays_primitives_to_object: Story;
export declare const Case_5_1_21_operation_bindings_kafka_remove_object_property: Story;
export declare const Case_5_1_22_operation_bindings_kafka_add_object_property: Story;
export declare const Case_6_1_operation_x_second_added: Story;
export declare const Case_6_2_operation_x_second_removed: Story;
export declare const Case_6_3_operation_x_second_changed: Story;
export declare const Case_6_4_operation_x_first_and_x_second_added: Story;
export declare const Case_6_5_operation_x_first_and_x_second_removed: Story;
