// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
/**
 * Screenshot tests for OpenAPI Operation Diffs Suite - Cookies: every case in display modes
 * `detailed` and `simple` (the same story, `displayMode` passed as a story arg).
 */
import { storyPageWithArgs } from './service/storybook-service'
import { waitForOpenApiOperationDiffsViewer, waitForRenderingComplete } from './service/viewer-waits'

/** [case id, story id, test ids clicked before the capture]. */
const CASES: ReadonlyArray<readonly [string, string, readonly string[]]> = [
  ['01-entry-added', 'openapi-operation-diffs-suite-cookies--case-01-entry-added', []],
  ['02-entry-removed', 'openapi-operation-diffs-suite-cookies--case-02-entry-removed', []],
  ['03-entry-renamed', 'openapi-operation-diffs-suite-cookies--case-03-entry-renamed', []],
  ['04-required-added', 'openapi-operation-diffs-suite-cookies--case-04-required-added', []],
  ['05-required-removed', 'openapi-operation-diffs-suite-cookies--case-05-required-removed', []],
  ['06-description-added', 'openapi-operation-diffs-suite-cookies--case-06-description-added', []],
  ['07-description-removed', 'openapi-operation-diffs-suite-cookies--case-07-description-removed', []],
  ['08-description-changed', 'openapi-operation-diffs-suite-cookies--case-08-description-changed', []],
  ['09-deprecated-added', 'openapi-operation-diffs-suite-cookies--case-09-deprecated-added', []],
  ['10-deprecated-removed', 'openapi-operation-diffs-suite-cookies--case-10-deprecated-removed', []],
  ['11-schema-to-content', 'openapi-operation-diffs-suite-cookies--case-11-schema-to-content', []],
  ['12-content-to-schema', 'openapi-operation-diffs-suite-cookies--case-12-content-to-schema', []],
  ['13-content-media-type-renamed', 'openapi-operation-diffs-suite-cookies--case-13-content-media-type-renamed', []],
  ['14-extension-added', 'openapi-operation-diffs-suite-cookies--case-14-extension-added', []],
  ['15-extension-removed', 'openapi-operation-diffs-suite-cookies--case-15-extension-removed', []],
  ['16-extension-changed', 'openapi-operation-diffs-suite-cookies--case-16-extension-changed', []],
  ['17-extension-moved-to-schema', 'openapi-operation-diffs-suite-cookies--case-17-extension-moved-to-schema', []],
  ['18-extension-moved-to-entry', 'openapi-operation-diffs-suite-cookies--case-18-extension-moved-to-entry', []],
  ['19-all-added', 'openapi-operation-diffs-suite-cookies--case-19-all-added', []],
  ['20-all-removed', 'openapi-operation-diffs-suite-cookies--case-20-all-removed', []],
  ['21-description-moved-entry-to-schema', 'openapi-operation-diffs-suite-cookies--case-21-description-moved-entry-to-schema', []],
  ['22-description-moved-schema-to-entry', 'openapi-operation-diffs-suite-cookies--case-22-description-moved-schema-to-entry', []],
  ['23-description-entry-removed-schema-added', 'openapi-operation-diffs-suite-cookies--case-23-description-entry-removed-schema-added', []],
  ['24-description-schema-removed-entry-added', 'openapi-operation-diffs-suite-cookies--case-24-description-schema-removed-entry-added', []],
  ['25-description-both-places-changed', 'openapi-operation-diffs-suite-cookies--case-25-description-both-places-changed', []],
  ['26-description-schema-changed-under-entry', 'openapi-operation-diffs-suite-cookies--case-26-description-schema-changed-under-entry', []],
]

describe('OpenAPI Operation Diffs Suite - Cookies', () => {
  beforeEach(async () => {
    await jestPuppeteer.resetPage()
  })

  describe.each(['detailed', 'simple'])('display mode %s', (displayMode) => {
    it.each(CASES)('%s', async (_caseId, storyId, clicks) => {
      const story = await storyPageWithArgs(page, storyId, { displayMode })
      const component = await story.viewComponent()
      await waitForOpenApiOperationDiffsViewer(page)
      for (const testId of clicks) {
        await page.click(`[data-testid="${testId}"]`)
        await waitForRenderingComplete(page)
      }
      expect(await component.captureScreenshot()).toMatchImageSnapshot()
    })
  })
})
