// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
/**
 * Screenshot tests for OpenAPI Operation Diffs Suite - Security: every case in display modes
 * `detailed` and `simple` (the same story, `displayMode` passed as a story arg).
 */
import { storyPageWithArgs } from './service/storybook-service'
import { waitForOpenApiOperationDiffsViewer, waitForRenderingComplete } from './service/viewer-waits'

/** [case id, story id, test ids clicked before the capture]. */
const CASES: ReadonlyArray<readonly [string, string, readonly string[]]> = [
  ['01-security-added', 'openapi-operation-diffs-suite-security--case-01-security-added', []],
  ['02-security-removed', 'openapi-operation-diffs-suite-security--case-02-security-removed', []],
  ['03-document-security-overridden', 'openapi-operation-diffs-suite-security--case-03-document-security-overridden', []],
  ['04-document-security-override-removed', 'openapi-operation-diffs-suite-security--case-04-document-security-override-removed', []],
  ['05-alternative-added', 'openapi-operation-diffs-suite-security--case-05-alternative-added', ['security-alternative-1']],
  ['06-alternative-removed', 'openapi-operation-diffs-suite-security--case-06-alternative-removed', ['security-alternative-1']],
  ['07-anonymous-alternative-added', 'openapi-operation-diffs-suite-security--case-07-anonymous-alternative-added', ['security-alternative-1']],
  ['08-anonymous-alternative-removed', 'openapi-operation-diffs-suite-security--case-08-anonymous-alternative-removed', ['security-alternative-1']],
  ['09-scheme-added-to-alternative', 'openapi-operation-diffs-suite-security--case-09-scheme-added-to-alternative', []],
  ['10-scheme-removed-from-alternative', 'openapi-operation-diffs-suite-security--case-10-scheme-removed-from-alternative', []],
  ['11-required-scope-added', 'openapi-operation-diffs-suite-security--case-11-required-scope-added', []],
  ['12-required-scope-removed', 'openapi-operation-diffs-suite-security--case-12-required-scope-removed', []],
  ['13-scheme-description-added', 'openapi-operation-diffs-suite-security--case-13-scheme-description-added', []],
  ['14-scheme-description-removed', 'openapi-operation-diffs-suite-security--case-14-scheme-description-removed', []],
  ['15-scheme-type-changed', 'openapi-operation-diffs-suite-security--case-15-scheme-type-changed', []],
  ['16-scheme-definition-added', 'openapi-operation-diffs-suite-security--case-16-scheme-definition-added', []],
  ['17-scheme-definition-removed', 'openapi-operation-diffs-suite-security--case-17-scheme-definition-removed', []],
  ['18-api-key-location-changed', 'openapi-operation-diffs-suite-security--case-18-api-key-location-changed', []],
  ['19-api-key-name-changed', 'openapi-operation-diffs-suite-security--case-19-api-key-name-changed', []],
  ['20-http-scheme-changed', 'openapi-operation-diffs-suite-security--case-20-http-scheme-changed', []],
  ['21-bearer-format-added', 'openapi-operation-diffs-suite-security--case-21-bearer-format-added', []],
  ['22-bearer-format-removed', 'openapi-operation-diffs-suite-security--case-22-bearer-format-removed', []],
  ['23-openid-connect-url-changed', 'openapi-operation-diffs-suite-security--case-23-openid-connect-url-changed', []],
  ['24-oauth-flow-added', 'openapi-operation-diffs-suite-security--case-24-oauth-flow-added', []],
  ['25-oauth-flow-removed', 'openapi-operation-diffs-suite-security--case-25-oauth-flow-removed', []],
  ['26-token-url-changed', 'openapi-operation-diffs-suite-security--case-26-token-url-changed', []],
  ['27-refresh-url-added', 'openapi-operation-diffs-suite-security--case-27-refresh-url-added', []],
  ['28-refresh-url-removed', 'openapi-operation-diffs-suite-security--case-28-refresh-url-removed', []],
  ['29-flow-scope-added', 'openapi-operation-diffs-suite-security--case-29-flow-scope-added', []],
  ['30-flow-scope-removed', 'openapi-operation-diffs-suite-security--case-30-flow-scope-removed', []],
  ['31-flow-scope-description-changed', 'openapi-operation-diffs-suite-security--case-31-flow-scope-description-changed', []],
]

describe('OpenAPI Operation Diffs Suite - Security', () => {
  beforeEach(async () => {
    await jestPuppeteer.resetPage()
  })

  describe.each(['detailed', 'simple'])('display mode %s', (displayMode) => {
    it.each(CASES)('%s', async (_caseId, storyId, clicks) => {
      const story = await storyPageWithArgs(page, storyId, { displayMode })
      const component = await story.viewComponent()
      await waitForOpenApiOperationDiffsViewer(page)
      for (const testId of clicks) {
        await page.click(`[data-testid="${testId}"]`)
        await waitForRenderingComplete(page)
      }
      expect(await component.captureScreenshot()).toMatchImageSnapshot()
    })
  })
})
