// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
/**
 * Screenshot tests for OpenAPI Operation Diffs Suite - Response Body: every case in display modes
 * `detailed` and `simple` (the same story, `displayMode` passed as a story arg).
 */
import { storyPageWithArgs } from './service/storybook-service'
import { waitForOpenApiOperationDiffsViewer, waitForRenderingComplete } from './service/viewer-waits'

/** [case id, story id, test ids clicked before the capture]. */
const CASES: ReadonlyArray<readonly [string, string, readonly string[]]> = [
  ['01-body-added', 'openapi-operation-diffs-suite-response-body--case-01-body-added', []],
  ['02-body-removed', 'openapi-operation-diffs-suite-response-body--case-02-body-removed', []],
  ['08-media-type-added', 'openapi-operation-diffs-suite-response-body--case-08-media-type-added', []],
  ['09-media-type-removed', 'openapi-operation-diffs-suite-response-body--case-09-media-type-removed', []],
  ['10-media-type-renamed', 'openapi-operation-diffs-suite-response-body--case-10-media-type-renamed', []],
  ['15-schema-added', 'openapi-operation-diffs-suite-response-body--case-15-schema-added', []],
  ['16-schema-removed', 'openapi-operation-diffs-suite-response-body--case-16-schema-removed', []],
  ['17-schema-property-added', 'openapi-operation-diffs-suite-response-body--case-17-schema-property-added', []],
  ['18-schema-property-removed', 'openapi-operation-diffs-suite-response-body--case-18-schema-property-removed', []],
  ['19-schema-type-changed', 'openapi-operation-diffs-suite-response-body--case-19-schema-type-changed', []],
  ['22-media-type-extension-added', 'openapi-operation-diffs-suite-response-body--case-22-media-type-extension-added', []],
  ['23-media-type-extension-removed', 'openapi-operation-diffs-suite-response-body--case-23-media-type-extension-removed', []],
  ['25-media-type-extension-shadows-schema-root', 'openapi-operation-diffs-suite-response-body--case-25-media-type-extension-shadows-schema-root', []],
]

describe('OpenAPI Operation Diffs Suite - Response Body', () => {
  beforeEach(async () => {
    await jestPuppeteer.resetPage()
  })

  describe.each(['detailed', 'simple'])('display mode %s', (displayMode) => {
    it.each(CASES)('%s', async (_caseId, storyId, clicks) => {
      const story = await storyPageWithArgs(page, storyId, { displayMode })
      const component = await story.viewComponent()
      await waitForOpenApiOperationDiffsViewer(page)
      for (const testId of clicks) {
        await page.click(`[data-testid="${testId}"]`)
        await waitForRenderingComplete(page)
      }
      expect(await component.captureScreenshot()).toMatchImageSnapshot()
    })
  })
})
