// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
/**
 * Screenshot tests for OpenAPI Operation Diffs Suite - Responses: every case in display modes
 * `detailed` and `simple` (the same story, `displayMode` passed as a story arg).
 */
import { storyPageWithArgs } from './service/storybook-service'
import { waitForOpenApiOperationDiffsViewer, waitForRenderingComplete } from './service/viewer-waits'

/** [case id, story id, test ids clicked before the capture]. */
const CASES: ReadonlyArray<readonly [string, string, readonly string[]]> = [
  ['01-response-1xx-added', 'openapi-operation-diffs-suite-responses--case-01-response-1-xx-added', ['response-code-101']],
  ['02-response-1xx-removed', 'openapi-operation-diffs-suite-responses--case-02-response-1-xx-removed', ['response-code-101']],
  ['03-response-2xx-added', 'openapi-operation-diffs-suite-responses--case-03-response-2-xx-added', ['response-code-201']],
  ['04-response-2xx-removed', 'openapi-operation-diffs-suite-responses--case-04-response-2-xx-removed', ['response-code-201']],
  ['05-response-3xx-added', 'openapi-operation-diffs-suite-responses--case-05-response-3-xx-added', ['response-code-303']],
  ['06-response-3xx-removed', 'openapi-operation-diffs-suite-responses--case-06-response-3-xx-removed', ['response-code-303']],
  ['07-response-4xx-added', 'openapi-operation-diffs-suite-responses--case-07-response-4-xx-added', ['response-code-404']],
  ['08-response-4xx-removed', 'openapi-operation-diffs-suite-responses--case-08-response-4-xx-removed', ['response-code-404']],
  ['09-response-5xx-added', 'openapi-operation-diffs-suite-responses--case-09-response-5-xx-added', ['response-code-500']],
  ['10-response-5xx-removed', 'openapi-operation-diffs-suite-responses--case-10-response-5-xx-removed', ['response-code-500']],
  ['11-response-range-added', 'openapi-operation-diffs-suite-responses--case-11-response-range-added', ['response-code-5XX']],
  ['12-response-range-removed', 'openapi-operation-diffs-suite-responses--case-12-response-range-removed', ['response-code-5XX']],
  ['13-response-default-added', 'openapi-operation-diffs-suite-responses--case-13-response-default-added', ['response-code-default']],
  ['14-response-default-removed', 'openapi-operation-diffs-suite-responses--case-14-response-default-removed', ['response-code-default']],
  ['15-code-case-renamed', 'openapi-operation-diffs-suite-responses--case-15-code-case-renamed', ['response-code-4XX']],
  ['16-code-renamed-and-description-changed', 'openapi-operation-diffs-suite-responses--case-16-code-renamed-and-description-changed', ['response-code-4XX']],
  ['17-description-changed', 'openapi-operation-diffs-suite-responses--case-17-description-changed', []],
  ['18-description-changed-non-initial-code', 'openapi-operation-diffs-suite-responses--case-18-description-changed-non-initial-code', []],
  ['19-response-extension-added', 'openapi-operation-diffs-suite-responses--case-19-response-extension-added', []],
  ['20-response-extension-removed', 'openapi-operation-diffs-suite-responses--case-20-response-extension-removed', []],
  ['21-response-extension-changed', 'openapi-operation-diffs-suite-responses--case-21-response-extension-changed', []],
  ['22-responses-extension-added', 'openapi-operation-diffs-suite-responses--case-22-responses-extension-added', []],
  ['23-responses-extension-removed', 'openapi-operation-diffs-suite-responses--case-23-responses-extension-removed', []],
  ['24-responses-and-response-extensions-changed', 'openapi-operation-diffs-suite-responses--case-24-responses-and-response-extensions-changed', []],
  ['25-changes-of-different-severity', 'openapi-operation-diffs-suite-responses--case-25-changes-of-different-severity', []],
]

describe('OpenAPI Operation Diffs Suite - Responses', () => {
  beforeEach(async () => {
    await jestPuppeteer.resetPage()
  })

  describe.each(['detailed', 'simple'])('display mode %s', (displayMode) => {
    it.each(CASES)('%s', async (_caseId, storyId, clicks) => {
      const story = await storyPageWithArgs(page, storyId, { displayMode })
      const component = await story.viewComponent()
      await waitForOpenApiOperationDiffsViewer(page)
      for (const testId of clicks) {
        await page.click(`[data-testid="${testId}"]`)
        await waitForRenderingComplete(page)
      }
      expect(await component.captureScreenshot()).toMatchImageSnapshot()
    })
  })
})
