import type { Meta, StoryObj } from '@storybook/react';
import { GraphQLCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<GraphQLCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AddDescriptionForFieldOfOutputInterface: Story;
export declare const AddDescriptionForOutputInterface: Story;
export declare const AddEnumValueOfFieldInOutputInterface: Story;
export declare const AddNewFieldInOutputInterface: Story;
export declare const ChangeFieldTypeOfOutputInterface: Story;
export declare const DeleteDescriptionForFieldOfOutputInterface: Story;
export declare const DeleteDescriptionOfOutputInterface: Story;
export declare const MarkMandatoryFieldOfOutputInterfaceAsOptional: Story;
export declare const MarkOptionalFieldOfOutputInterfaceAsMandatory: Story;
export declare const RemoveEnumValueOfFieldInOutputInterface: Story;
export declare const RemoveFieldFromOutputInterface: Story;
export declare const UpdateDescriptionForFieldOfOutputInterface: Story;
export declare const UpdateDescriptionOfOutputInterface: Story;
