import type { Meta, StoryObj } from '@storybook/react';
import { GraphQLCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<GraphQLCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AddDescriptionForFieldOfOutputObjectType: Story;
export declare const AddDescriptionForOutputObjectType: Story;
export declare const AddEnumValueOfFieldInOutputObjectType: Story;
export declare const AddNewFieldInOutputObjectType: Story;
export declare const ChangeFieldTypeOfOutputObjectType: Story;
export declare const DeleteDescriptionForFieldOfOutputObjectType: Story;
export declare const DeleteDescriptionOfOutputObjectType: Story;
export declare const MarkMandatoryFieldOfOutputObjectTypeAsOptional: Story;
export declare const MarkOptionalFieldOfOutputObjectTypeAsMandatory: Story;
export declare const RemoveEnumValueOfFieldInOutputObjectType: Story;
export declare const RemoveFieldFromOutputObjectType: Story;
export declare const UpdateDescriptionForFieldOfOutputObjectType: Story;
export declare const UpdateDescriptionOfOutputObjectType: Story;
