import type { Meta, StoryObj } from '@storybook/react';
import { GraphQLCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<GraphQLCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AddDescriptionForEnumValueInOutputType: Story;
export declare const AddEnumValueInOutputType: Story;
export declare const AddListTypeForOutputType: Story;
export declare const ChangeDescriptionForEnumValueInOutputType: Story;
export declare const ChangeOutputType: Story;
export declare const DeleteDescriptionForEnumValueInOutputType: Story;
export declare const MarkMandatoryOutputTypeAsOptional: Story;
export declare const MarkOptionalOutputTypeAsMandatory: Story;
export declare const RemoveEnumValueInOutputType: Story;
