import type { Meta, StoryObj } from '@storybook/react';
import { DdlCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<DdlCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const BinaryToText: Story;
export declare const BoolToInt: Story;
export declare const DateToTimestamp: Story;
export declare const DecreaseDecimalPrecision: Story;
export declare const DecreaseDecimalScale: Story;
export declare const DecreaseVarcharSize: Story;
export declare const EnumToText: Story;
export declare const FloatToDecimal: Story;
export declare const IncreaseDecimalPrecision: Story;
export declare const IncreaseDecimalScale: Story;
export declare const IncreaseVarcharSize: Story;
export declare const IntToBool: Story;
export declare const IntegerToVarchar: Story;
export declare const JsonToJsonb: Story;
export declare const JsonToText: Story;
export declare const JsonbToJson: Story;
export declare const NarrowBigintToSmallint: Story;
export declare const NarrowCrossFamilyToText: Story;
export declare const NarrowDoubleToReal: Story;
export declare const NumericToFloat: Story;
export declare const NumericToInteger: Story;
export declare const TextToBinary: Story;
export declare const TextToEnum: Story;
export declare const TextToJson: Story;
export declare const TextToUuid: Story;
export declare const TextToVarcharLimited: Story;
export declare const TextToVarcharUnlimited: Story;
export declare const TimestampToDate: Story;
export declare const UuidToText: Story;
export declare const VarcharToInteger: Story;
export declare const VarcharToText: Story;
export declare const WidenBigintToNumeric: Story;
export declare const WidenFloatToDouble: Story;
export declare const WidenIntegerToBigint: Story;
export declare const WidenIntegerToNumeric: Story;
export declare const WidenSmallintToInteger: Story;
