import type { Meta, StoryObj } from '@storybook/react';
import { GraphQLCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<GraphQLCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AddDescriptionForFieldOfInterfaceType: Story;
export declare const AddDescriptionForInterfaceType: Story;
export declare const AddInterfaceForObjectType: Story;
export declare const AddNewFieldInInterfaceType: Story;
export declare const ChangeFieldTypeOfInterfaceType: Story;
export declare const ChangeInterfaceForObjectType: Story;
export declare const DeleteDescriptionForFieldOfInterfaceType: Story;
export declare const DeleteDescriptionForInterfaceType: Story;
export declare const DeleteInterfaceForObjectType: Story;
export declare const MarkMandatoryFieldOfInterfaceTypeAsOptional: Story;
export declare const MarkOptionalFieldOfInterfaceTypeAsMandatory: Story;
export declare const RemoveFieldFromInterfaceType: Story;
export declare const UpdateDescriptionForFieldOfInterfaceType: Story;
export declare const UpdateDescriptionForInterfaceType: Story;
