/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/array-validations/items-count/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/array-validations/items-count/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/array-validations/items-count/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Array Validations Items Count",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_min_items_added: Story = createCaseStory("001-min-items-added");
export const Case_002_min_items_removed: Story = createCaseStory("002-min-items-removed");
export const Case_003_min_items_replaced: Story = createCaseStory("003-min-items-replaced");
export const Case_004_max_items_added: Story = createCaseStory("004-max-items-added");
export const Case_005_max_items_removed: Story = createCaseStory("005-max-items-removed");
export const Case_006_max_items_replaced: Story = createCaseStory("006-max-items-replaced");
export const Case_007_max_items_added_to_min: Story = createCaseStory("007-max-items-added-to-min");
export const Case_008_min_items_added_to_max: Story = createCaseStory("008-min-items-added-to-max");
export const Case_009_items_count_both_added: Story = createCaseStory("009-items-count-both-added");
export const Case_010_max_items_removed_keep_min: Story = createCaseStory("010-max-items-removed-keep-min");
export const Case_011_min_items_removed_keep_max: Story = createCaseStory("011-min-items-removed-keep-max");
export const Case_012_items_count_both_removed: Story = createCaseStory("012-items-count-both-removed");
export const Case_013_items_count_replace_min: Story = createCaseStory("013-items-count-replace-min");
export const Case_014_items_count_replace_max: Story = createCaseStory("014-items-count-replace-max");
export const Case_015_items_count_replace_both: Story = createCaseStory("015-items-count-replace-both");
export const Case_016_min_items_added_max_items_removed: Story = createCaseStory("016-min-items-added-max-items-removed");
export const Case_017_max_items_added_min_items_removed: Story = createCaseStory("017-max-items-added-min-items-removed");
export const Case_018_min_items_added_max_items_replaced: Story = createCaseStory("018-min-items-added-max-items-replaced");
export const Case_019_min_items_removed_max_items_replaced: Story = createCaseStory("019-min-items-removed-max-items-replaced");
export const Case_020_max_items_added_min_items_replaced: Story = createCaseStory("020-max-items-added-min-items-replaced");
export const Case_021_max_items_removed_min_items_replaced: Story = createCaseStory("021-max-items-removed-min-items-replaced");
export const Case_022_unique_items_true_added: Story = createCaseStory("022-unique-items-true-added");
export const Case_023_unique_items_false_added: Story = createCaseStory("023-unique-items-false-added");
export const Case_024_unique_items_true_removed: Story = createCaseStory("024-unique-items-true-removed");
export const Case_025_unique_items_false_removed: Story = createCaseStory("025-unique-items-false-removed");
export const Case_026_unique_items_true_to_false: Story = createCaseStory("026-unique-items-true-to-false");
export const Case_027_unique_items_false_to_true: Story = createCaseStory("027-unique-items-false-to-true");
