/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/array-indexed-items/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/array-indexed-items/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/array-indexed-items/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Array Indexed Items",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_add_one_indexed_item_string: Story = createCaseStory("001-add-one-indexed-item-string");
export const Case_002_remove_one_indexed_item_string: Story = createCaseStory("002-remove-one-indexed-item-string");
export const Case_003_add_two_indexed_items_string: Story = createCaseStory("003-add-two-indexed-items-string");
export const Case_004_remove_two_indexed_items_string: Story = createCaseStory("004-remove-two-indexed-items-string");
export const Case_005_add_one_indexed_item_number: Story = createCaseStory("005-add-one-indexed-item-number");
export const Case_006_remove_one_indexed_item_number: Story = createCaseStory("006-remove-one-indexed-item-number");
export const Case_007_add_two_indexed_items_number: Story = createCaseStory("007-add-two-indexed-items-number");
export const Case_008_remove_two_indexed_items_number: Story = createCaseStory("008-remove-two-indexed-items-number");
export const Case_009_add_one_indexed_item_integer: Story = createCaseStory("009-add-one-indexed-item-integer");
export const Case_010_remove_one_indexed_item_integer: Story = createCaseStory("010-remove-one-indexed-item-integer");
export const Case_011_add_two_indexed_items_integer: Story = createCaseStory("011-add-two-indexed-items-integer");
export const Case_012_remove_two_indexed_items_integer: Story = createCaseStory("012-remove-two-indexed-items-integer");
export const Case_013_add_one_indexed_item_boolean: Story = createCaseStory("013-add-one-indexed-item-boolean");
export const Case_014_remove_one_indexed_item_boolean: Story = createCaseStory("014-remove-one-indexed-item-boolean");
export const Case_015_add_two_indexed_items_boolean: Story = createCaseStory("015-add-two-indexed-items-boolean");
export const Case_016_remove_two_indexed_items_boolean: Story = createCaseStory("016-remove-two-indexed-items-boolean");
export const Case_017_add_one_indexed_item_array: Story = createCaseStory("017-add-one-indexed-item-array");
export const Case_018_remove_one_indexed_item_array: Story = createCaseStory("018-remove-one-indexed-item-array");
export const Case_019_add_two_indexed_items_array: Story = createCaseStory("019-add-two-indexed-items-array");
export const Case_020_remove_two_indexed_items_array: Story = createCaseStory("020-remove-two-indexed-items-array");
export const Case_021_add_one_indexed_item_object: Story = createCaseStory("021-add-one-indexed-item-object");
export const Case_022_remove_one_indexed_item_object: Story = createCaseStory("022-remove-one-indexed-item-object");
export const Case_023_add_two_indexed_items_object: Story = createCaseStory("023-add-two-indexed-items-object");
export const Case_024_remove_two_indexed_items_object: Story = createCaseStory("024-remove-two-indexed-items-object");
