/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/circular/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./circular-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/circular/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/circular/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Circular",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_self_object_description_updated: Story = createCaseStory("001-self-object-description-updated");
export const Case_002_self_object_cycle_removed: Story = createCaseStory("002-self-object-cycle-removed");
export const Case_003_self_object_cycle_added: Story = createCaseStory("003-self-object-cycle-added");
export const Case_004_self_array_description_updated: Story = createCaseStory("004-self-array-description-updated");
export const Case_005_self_array_cycle_removed: Story = createCaseStory("005-self-array-cycle-removed");
export const Case_006_self_array_cycle_added: Story = createCaseStory("006-self-array-cycle-added");
export const Case_007_chain_three_hop_description_updated: Story = createCaseStory("007-chain-three-hop-description-updated");
export const Case_008_chain_three_hop_cycle_removed: Story = createCaseStory("008-chain-three-hop-cycle-removed");
export const Case_009_chain_three_hop_cycle_added: Story = createCaseStory("009-chain-three-hop-cycle-added");
export const Case_010_combiner_variant_cycle_description_updated: Story = createCaseStory("010-combiner-variant-cycle-description-updated");
export const Case_011_combiner_variant_cycle_cycle_removed: Story = createCaseStory("011-combiner-variant-cycle-cycle-removed");
export const Case_012_combiner_variant_cycle_cycle_added: Story = createCaseStory("012-combiner-variant-cycle-cycle-added");
