/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/description-changes/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/description-changes/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/description-changes/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Description Changes",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_description_added: Story = createCaseStory("001-description-added");
export const Case_002_description_removed: Story = createCaseStory("002-description-removed");
export const Case_003_description_replaced: Story = createCaseStory("003-description-replaced");
export const Case_004_description_with_enum_added: Story = createCaseStory("004-description-with-enum-added");
export const Case_005_description_with_enum_removed: Story = createCaseStory("005-description-with-enum-removed");
export const Case_006_description_with_enum_replaced: Story = createCaseStory("006-description-with-enum-replaced");
export const Case_007_unchanged_description_short: Story = createCaseStory("007-unchanged-description-short");
export const Case_008_unchanged_description_long: Story = createCaseStory("008-unchanged-description-long");
export const Case_009_description_changed_short_line_text_changed: Story = createCaseStory("009-description-changed-short-line-text-changed");
export const Case_010_description_changed_short_lines_text_changed: Story = createCaseStory("010-description-changed-short-lines-text-changed");
export const Case_011_description_changed_long_line_text_changed: Story = createCaseStory("011-description-changed-long-line-text-changed");
export const Case_012_description_changed_long_lines_text_changed: Story = createCaseStory("012-description-changed-long-lines-text-changed");
export const Case_013_description_changed_short_line_to_short_lines: Story = createCaseStory("013-description-changed-short-line-to-short-lines");
export const Case_014_description_changed_short_line_to_long_line: Story = createCaseStory("014-description-changed-short-line-to-long-line");
export const Case_015_description_changed_short_line_to_long_lines: Story = createCaseStory("015-description-changed-short-line-to-long-lines");
export const Case_016_description_changed_short_lines_to_short_line: Story = createCaseStory("016-description-changed-short-lines-to-short-line");
export const Case_017_description_changed_short_lines_to_long_line: Story = createCaseStory("017-description-changed-short-lines-to-long-line");
export const Case_018_description_changed_short_lines_to_long_lines: Story = createCaseStory("018-description-changed-short-lines-to-long-lines");
export const Case_019_description_changed_long_line_to_short_line: Story = createCaseStory("019-description-changed-long-line-to-short-line");
export const Case_020_description_changed_long_line_to_short_lines: Story = createCaseStory("020-description-changed-long-line-to-short-lines");
export const Case_021_description_changed_long_line_to_long_lines: Story = createCaseStory("021-description-changed-long-line-to-long-lines");
export const Case_022_description_changed_long_lines_to_short_line: Story = createCaseStory("022-description-changed-long-lines-to-short-line");
export const Case_023_description_changed_long_lines_to_short_lines: Story = createCaseStory("023-description-changed-long-lines-to-short-lines");
export const Case_024_description_changed_long_lines_to_long_line: Story = createCaseStory("024-description-changed-long-lines-to-long-line");
export const Case_025_unchanged_description_short_multiline: Story = createCaseStory("025-unchanged-description-short-multiline");
export const Case_026_unchanged_description_long_multiline: Story = createCaseStory("026-unchanged-description-long-multiline");
