/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/extended/array/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/extended/array/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/extended/array/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Extended Array",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_additional_items_added: Story = createCaseStory("001-additional-items-added");
export const Case_002_additional_items_removed: Story = createCaseStory("002-additional-items-removed");
export const Case_003_additional_items_type_changed: Story = createCaseStory("003-additional-items-type-changed");
export const Case_004_items_schema_to_array: Story = createCaseStory("004-items-schema-to-array");
export const Case_005_tuple_item_appended: Story = createCaseStory("005-tuple-item-appended");
export const Case_006_tuple_item_removed: Story = createCaseStory("006-tuple-item-removed");
export const Case_007_items_schema_description_changed: Story = createCaseStory("007-items-schema-description-changed");
export const Case_008_unique_items_added: Story = createCaseStory("008-unique-items-added");
export const Case_009_unique_items_removed: Story = createCaseStory("009-unique-items-removed");
