/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/extended/combiners-two-level/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/extended/combiners-two-level/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/extended/combiners-two-level/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Extended Combiners Two Level Samples",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_two_level_append_variant_string: Story = createCaseStory("001-two-level-append-variant-string");
export const Case_002_two_level_append_variant_object: Story = createCaseStory("002-two-level-append-variant-object");
export const Case_003_two_level_append_variant_array: Story = createCaseStory("003-two-level-append-variant-array");
export const Case_004_two_level_remove_variant_string: Story = createCaseStory("004-two-level-remove-variant-string");
export const Case_005_two_level_remove_variant_object: Story = createCaseStory("005-two-level-remove-variant-object");
export const Case_006_two_level_remove_variant_array: Story = createCaseStory("006-two-level-remove-variant-array");
export const Case_007_two_level_change_variant_string: Story = createCaseStory("007-two-level-change-variant-string");
export const Case_008_two_level_change_variant_object: Story = createCaseStory("008-two-level-change-variant-object");
export const Case_009_two_level_change_variant_array: Story = createCaseStory("009-two-level-change-variant-array");
export const Case_010_two_level_append_variant_nested_combiner: Story = createCaseStory("010-two-level-append-variant-nested-combiner");
export const Case_011_two_level_remove_variant_nested_combiner: Story = createCaseStory("011-two-level-remove-variant-nested-combiner");
