/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-validations/example/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-validations/example/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-validations/example/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Object Validations Example",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_example_added_empty_object: Story = createCaseStory("001-example-added-empty-object");
export const Case_002_example_added_object: Story = createCaseStory("002-example-added-object");
export const Case_003_example_removed_empty_object: Story = createCaseStory("003-example-removed-empty-object");
export const Case_004_example_removed_object: Story = createCaseStory("004-example-removed-object");
export const Case_005_example_replaced_empty_to_object: Story = createCaseStory("005-example-replaced-empty-to-object");
export const Case_006_example_replaced_object_to_empty: Story = createCaseStory("006-example-replaced-object-to-empty");
export const Case_007_example_replaced_object_to_object: Story = createCaseStory("007-example-replaced-object-to-object");
