/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-additional-properties/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-additional-properties/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-additional-properties/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Object Additional Properties",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_add_additional_properties_rule1_string: Story = createCaseStory("001-add-additional-properties-rule1-string");
export const Case_002_remove_additional_properties_rule1_string: Story = createCaseStory("002-remove-additional-properties-rule1-string");
export const Case_003_add_additional_properties_false_string: Story = createCaseStory("003-add-additional-properties-false-string");
export const Case_004_remove_additional_properties_false_string: Story = createCaseStory("004-remove-additional-properties-false-string");
export const Case_005_change_additional_properties_rule1_to_false_string: Story = createCaseStory("005-change-additional-properties-rule1-to-false-string");
export const Case_006_change_additional_properties_false_to_rule1_string: Story = createCaseStory("006-change-additional-properties-false-to-rule1-string");
export const Case_007_add_additional_properties_rule1_number: Story = createCaseStory("007-add-additional-properties-rule1-number");
export const Case_008_remove_additional_properties_rule1_number: Story = createCaseStory("008-remove-additional-properties-rule1-number");
export const Case_009_add_additional_properties_false_number: Story = createCaseStory("009-add-additional-properties-false-number");
export const Case_010_remove_additional_properties_false_number: Story = createCaseStory("010-remove-additional-properties-false-number");
export const Case_011_change_additional_properties_rule1_to_false_number: Story = createCaseStory("011-change-additional-properties-rule1-to-false-number");
export const Case_012_change_additional_properties_false_to_rule1_number: Story = createCaseStory("012-change-additional-properties-false-to-rule1-number");
export const Case_013_add_additional_properties_rule1_integer: Story = createCaseStory("013-add-additional-properties-rule1-integer");
export const Case_014_remove_additional_properties_rule1_integer: Story = createCaseStory("014-remove-additional-properties-rule1-integer");
export const Case_015_add_additional_properties_false_integer: Story = createCaseStory("015-add-additional-properties-false-integer");
export const Case_016_remove_additional_properties_false_integer: Story = createCaseStory("016-remove-additional-properties-false-integer");
export const Case_017_change_additional_properties_rule1_to_false_integer: Story = createCaseStory("017-change-additional-properties-rule1-to-false-integer");
export const Case_018_change_additional_properties_false_to_rule1_integer: Story = createCaseStory("018-change-additional-properties-false-to-rule1-integer");
export const Case_019_add_additional_properties_rule1_boolean: Story = createCaseStory("019-add-additional-properties-rule1-boolean");
export const Case_020_remove_additional_properties_rule1_boolean: Story = createCaseStory("020-remove-additional-properties-rule1-boolean");
export const Case_021_add_additional_properties_false_boolean: Story = createCaseStory("021-add-additional-properties-false-boolean");
export const Case_022_remove_additional_properties_false_boolean: Story = createCaseStory("022-remove-additional-properties-false-boolean");
export const Case_023_change_additional_properties_rule1_to_false_boolean: Story = createCaseStory("023-change-additional-properties-rule1-to-false-boolean");
export const Case_024_change_additional_properties_false_to_rule1_boolean: Story = createCaseStory("024-change-additional-properties-false-to-rule1-boolean");
export const Case_025_add_additional_properties_rule1_array: Story = createCaseStory("025-add-additional-properties-rule1-array");
export const Case_026_remove_additional_properties_rule1_array: Story = createCaseStory("026-remove-additional-properties-rule1-array");
export const Case_027_add_additional_properties_false_array: Story = createCaseStory("027-add-additional-properties-false-array");
export const Case_028_remove_additional_properties_false_array: Story = createCaseStory("028-remove-additional-properties-false-array");
export const Case_029_change_additional_properties_rule1_to_false_array: Story = createCaseStory("029-change-additional-properties-rule1-to-false-array");
export const Case_030_change_additional_properties_false_to_rule1_array: Story = createCaseStory("030-change-additional-properties-false-to-rule1-array");
export const Case_031_add_additional_properties_rule1_object: Story = createCaseStory("031-add-additional-properties-rule1-object");
export const Case_032_remove_additional_properties_rule1_object: Story = createCaseStory("032-remove-additional-properties-rule1-object");
export const Case_033_add_additional_properties_false_object: Story = createCaseStory("033-add-additional-properties-false-object");
export const Case_034_remove_additional_properties_false_object: Story = createCaseStory("034-remove-additional-properties-false-object");
export const Case_035_change_additional_properties_rule1_to_false_object: Story = createCaseStory("035-change-additional-properties-rule1-to-false-object");
export const Case_036_change_additional_properties_false_to_rule1_object: Story = createCaseStory("036-change-additional-properties-false-to-rule1-object");
export const Case_037_one_of_variant2_add_additional_properties_rule1_string: Story = createCaseStory("037-one-of-variant2-add-additional-properties-rule1-string");
export const Case_038_one_of_variant2_remove_additional_properties_rule1_string: Story = createCaseStory("038-one-of-variant2-remove-additional-properties-rule1-string");
export const Case_039_one_of_variant2_add_additional_properties_false_string: Story = createCaseStory("039-one-of-variant2-add-additional-properties-false-string");
export const Case_040_one_of_variant2_remove_additional_properties_false_string: Story = createCaseStory("040-one-of-variant2-remove-additional-properties-false-string");
export const Case_041_one_of_variant2_change_additional_properties_rule1_to_false_string: Story = createCaseStory("041-one-of-variant2-change-additional-properties-rule1-to-false-string");
export const Case_042_one_of_variant2_change_additional_properties_false_to_rule1_string: Story = createCaseStory("042-one-of-variant2-change-additional-properties-false-to-rule1-string");
export const Case_043_one_of_variant2_add_additional_properties_rule1_number: Story = createCaseStory("043-one-of-variant2-add-additional-properties-rule1-number");
export const Case_044_one_of_variant2_remove_additional_properties_rule1_number: Story = createCaseStory("044-one-of-variant2-remove-additional-properties-rule1-number");
export const Case_045_one_of_variant2_add_additional_properties_false_number: Story = createCaseStory("045-one-of-variant2-add-additional-properties-false-number");
export const Case_046_one_of_variant2_remove_additional_properties_false_number: Story = createCaseStory("046-one-of-variant2-remove-additional-properties-false-number");
export const Case_047_one_of_variant2_change_additional_properties_rule1_to_false_number: Story = createCaseStory("047-one-of-variant2-change-additional-properties-rule1-to-false-number");
export const Case_048_one_of_variant2_change_additional_properties_false_to_rule1_number: Story = createCaseStory("048-one-of-variant2-change-additional-properties-false-to-rule1-number");
export const Case_049_one_of_variant2_add_additional_properties_rule1_integer: Story = createCaseStory("049-one-of-variant2-add-additional-properties-rule1-integer");
export const Case_050_one_of_variant2_remove_additional_properties_rule1_integer: Story = createCaseStory("050-one-of-variant2-remove-additional-properties-rule1-integer");
export const Case_051_one_of_variant2_add_additional_properties_false_integer: Story = createCaseStory("051-one-of-variant2-add-additional-properties-false-integer");
export const Case_052_one_of_variant2_remove_additional_properties_false_integer: Story = createCaseStory("052-one-of-variant2-remove-additional-properties-false-integer");
export const Case_053_one_of_variant2_change_additional_properties_rule1_to_false_integer: Story = createCaseStory("053-one-of-variant2-change-additional-properties-rule1-to-false-integer");
export const Case_054_one_of_variant2_change_additional_properties_false_to_rule1_integer: Story = createCaseStory("054-one-of-variant2-change-additional-properties-false-to-rule1-integer");
export const Case_055_one_of_variant2_add_additional_properties_rule1_boolean: Story = createCaseStory("055-one-of-variant2-add-additional-properties-rule1-boolean");
export const Case_056_one_of_variant2_remove_additional_properties_rule1_boolean: Story = createCaseStory("056-one-of-variant2-remove-additional-properties-rule1-boolean");
export const Case_057_one_of_variant2_add_additional_properties_false_boolean: Story = createCaseStory("057-one-of-variant2-add-additional-properties-false-boolean");
export const Case_058_one_of_variant2_remove_additional_properties_false_boolean: Story = createCaseStory("058-one-of-variant2-remove-additional-properties-false-boolean");
export const Case_059_one_of_variant2_change_additional_properties_rule1_to_false_boolean: Story = createCaseStory("059-one-of-variant2-change-additional-properties-rule1-to-false-boolean");
export const Case_060_one_of_variant2_change_additional_properties_false_to_rule1_boolean: Story = createCaseStory("060-one-of-variant2-change-additional-properties-false-to-rule1-boolean");
export const Case_061_one_of_variant2_add_additional_properties_rule1_array: Story = createCaseStory("061-one-of-variant2-add-additional-properties-rule1-array");
export const Case_062_one_of_variant2_remove_additional_properties_rule1_array: Story = createCaseStory("062-one-of-variant2-remove-additional-properties-rule1-array");
export const Case_063_one_of_variant2_add_additional_properties_false_array: Story = createCaseStory("063-one-of-variant2-add-additional-properties-false-array");
export const Case_064_one_of_variant2_remove_additional_properties_false_array: Story = createCaseStory("064-one-of-variant2-remove-additional-properties-false-array");
export const Case_065_one_of_variant2_change_additional_properties_rule1_to_false_array: Story = createCaseStory("065-one-of-variant2-change-additional-properties-rule1-to-false-array");
export const Case_066_one_of_variant2_change_additional_properties_false_to_rule1_array: Story = createCaseStory("066-one-of-variant2-change-additional-properties-false-to-rule1-array");
export const Case_067_one_of_variant2_add_additional_properties_rule1_object: Story = createCaseStory("067-one-of-variant2-add-additional-properties-rule1-object");
export const Case_068_one_of_variant2_remove_additional_properties_rule1_object: Story = createCaseStory("068-one-of-variant2-remove-additional-properties-rule1-object");
export const Case_069_one_of_variant2_add_additional_properties_false_object: Story = createCaseStory("069-one-of-variant2-add-additional-properties-false-object");
export const Case_070_one_of_variant2_remove_additional_properties_false_object: Story = createCaseStory("070-one-of-variant2-remove-additional-properties-false-object");
export const Case_071_one_of_variant2_change_additional_properties_rule1_to_false_object: Story = createCaseStory("071-one-of-variant2-change-additional-properties-rule1-to-false-object");
export const Case_072_one_of_variant2_change_additional_properties_false_to_rule1_object: Story = createCaseStory("072-one-of-variant2-change-additional-properties-false-to-rule1-object");
