/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-validations/properties-count/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-validations/properties-count/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-validations/properties-count/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Object Validations Properties Count",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_min_properties_added: Story = createCaseStory("001-min-properties-added");
export const Case_002_min_properties_removed: Story = createCaseStory("002-min-properties-removed");
export const Case_003_min_properties_replaced: Story = createCaseStory("003-min-properties-replaced");
export const Case_004_max_properties_added: Story = createCaseStory("004-max-properties-added");
export const Case_005_max_properties_removed: Story = createCaseStory("005-max-properties-removed");
export const Case_006_max_properties_replaced: Story = createCaseStory("006-max-properties-replaced");
export const Case_007_max_properties_added_to_min: Story = createCaseStory("007-max-properties-added-to-min");
export const Case_008_min_properties_added_to_max: Story = createCaseStory("008-min-properties-added-to-max");
export const Case_009_properties_count_both_added: Story = createCaseStory("009-properties-count-both-added");
export const Case_010_max_properties_removed_keep_min: Story = createCaseStory("010-max-properties-removed-keep-min");
export const Case_011_min_properties_removed_keep_max: Story = createCaseStory("011-min-properties-removed-keep-max");
export const Case_012_properties_count_both_removed: Story = createCaseStory("012-properties-count-both-removed");
export const Case_013_properties_count_replace_min: Story = createCaseStory("013-properties-count-replace-min");
export const Case_014_properties_count_replace_max: Story = createCaseStory("014-properties-count-replace-max");
export const Case_015_properties_count_replace_both: Story = createCaseStory("015-properties-count-replace-both");
export const Case_016_min_properties_added_max_properties_removed: Story = createCaseStory("016-min-properties-added-max-properties-removed");
export const Case_017_max_properties_added_min_properties_removed: Story = createCaseStory("017-max-properties-added-min-properties-removed");
export const Case_018_min_properties_added_max_properties_replaced: Story = createCaseStory("018-min-properties-added-max-properties-replaced");
export const Case_019_min_properties_removed_max_properties_replaced: Story = createCaseStory("019-min-properties-removed-max-properties-replaced");
export const Case_020_max_properties_added_min_properties_replaced: Story = createCaseStory("020-max-properties-added-min-properties-replaced");
export const Case_021_max_properties_removed_min_properties_replaced: Story = createCaseStory("021-max-properties-removed-min-properties-replaced");
