/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-validations/examples/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-validations/examples/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-validations/examples/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Object Validations Examples",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_examples_added_empty_object: Story = createCaseStory("001-examples-added-empty-object");
export const Case_002_examples_added_object: Story = createCaseStory("002-examples-added-object");
export const Case_003_examples_removed_empty_object: Story = createCaseStory("003-examples-removed-empty-object");
export const Case_004_examples_removed_object: Story = createCaseStory("004-examples-removed-object");
export const Case_005_examples_replaced_empty_to_object: Story = createCaseStory("005-examples-replaced-empty-to-object");
export const Case_006_examples_replaced_object_to_empty: Story = createCaseStory("006-examples-replaced-object-to-empty");
export const Case_007_examples_replaced_object_to_object: Story = createCaseStory("007-examples-replaced-object-to-object");
export const Case_008_examples_two_added_both_empty: Story = createCaseStory("008-examples-two-added-both-empty");
export const Case_009_examples_two_added_empty_and_object: Story = createCaseStory("009-examples-two-added-empty-and-object");
export const Case_010_examples_two_added_both_objects: Story = createCaseStory("010-examples-two-added-both-objects");
export const Case_011_examples_two_removed_both_empty: Story = createCaseStory("011-examples-two-removed-both-empty");
export const Case_012_examples_two_removed_empty_and_object: Story = createCaseStory("012-examples-two-removed-empty-and-object");
export const Case_013_examples_two_removed_both_objects: Story = createCaseStory("013-examples-two-removed-both-objects");
export const Case_014_examples_append_empty_to_empty: Story = createCaseStory("014-examples-append-empty-to-empty");
export const Case_015_examples_append_object_to_empty: Story = createCaseStory("015-examples-append-object-to-empty");
export const Case_016_examples_append_object_to_object: Story = createCaseStory("016-examples-append-object-to-object");
export const Case_017_examples_remove_empty_keep_object: Story = createCaseStory("017-examples-remove-empty-keep-object");
export const Case_018_examples_remove_object_keep_empty: Story = createCaseStory("018-examples-remove-object-keep-empty");
export const Case_019_examples_remove_first_of_two_empty: Story = createCaseStory("019-examples-remove-first-of-two-empty");
export const Case_020_examples_remove_first_of_two_objects: Story = createCaseStory("020-examples-remove-first-of-two-objects");
export const Case_021_examples_replace_empty_with_object: Story = createCaseStory("021-examples-replace-empty-with-object");
export const Case_022_examples_replace_object_with_empty: Story = createCaseStory("022-examples-replace-object-with-empty");
export const Case_023_examples_replace_object_with_object: Story = createCaseStory("023-examples-replace-object-with-object");
