/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-properties/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-properties/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-properties/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Object Properties",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_add_one_property_string: Story = createCaseStory("001-add-one-property-string");
export const Case_002_remove_one_property_string: Story = createCaseStory("002-remove-one-property-string");
export const Case_003_add_two_properties_string: Story = createCaseStory("003-add-two-properties-string");
export const Case_004_remove_two_properties_string: Story = createCaseStory("004-remove-two-properties-string");
export const Case_005_add_one_property_number: Story = createCaseStory("005-add-one-property-number");
export const Case_006_remove_one_property_number: Story = createCaseStory("006-remove-one-property-number");
export const Case_007_add_two_properties_number: Story = createCaseStory("007-add-two-properties-number");
export const Case_008_remove_two_properties_number: Story = createCaseStory("008-remove-two-properties-number");
export const Case_009_add_one_property_integer: Story = createCaseStory("009-add-one-property-integer");
export const Case_010_remove_one_property_integer: Story = createCaseStory("010-remove-one-property-integer");
export const Case_011_add_two_properties_integer: Story = createCaseStory("011-add-two-properties-integer");
export const Case_012_remove_two_properties_integer: Story = createCaseStory("012-remove-two-properties-integer");
export const Case_013_add_one_property_boolean: Story = createCaseStory("013-add-one-property-boolean");
export const Case_014_remove_one_property_boolean: Story = createCaseStory("014-remove-one-property-boolean");
export const Case_015_add_two_properties_boolean: Story = createCaseStory("015-add-two-properties-boolean");
export const Case_016_remove_two_properties_boolean: Story = createCaseStory("016-remove-two-properties-boolean");
export const Case_017_add_one_property_array: Story = createCaseStory("017-add-one-property-array");
export const Case_018_remove_one_property_array: Story = createCaseStory("018-remove-one-property-array");
export const Case_019_add_two_properties_array: Story = createCaseStory("019-add-two-properties-array");
export const Case_020_remove_two_properties_array: Story = createCaseStory("020-remove-two-properties-array");
export const Case_021_add_one_property_object: Story = createCaseStory("021-add-one-property-object");
export const Case_022_remove_one_property_object: Story = createCaseStory("022-remove-one-property-object");
export const Case_023_add_two_properties_object: Story = createCaseStory("023-add-two-properties-object");
export const Case_024_remove_two_properties_object: Story = createCaseStory("024-remove-two-properties-object");
export const Case_025_one_of_variant2_added_string: Story = createCaseStory("025-one-of-variant2-added-string");
export const Case_026_one_of_variant2_removed_string: Story = createCaseStory("026-one-of-variant2-removed-string");
export const Case_027_one_of_variant2_added_number: Story = createCaseStory("027-one-of-variant2-added-number");
export const Case_028_one_of_variant2_removed_number: Story = createCaseStory("028-one-of-variant2-removed-number");
export const Case_029_one_of_variant2_added_integer: Story = createCaseStory("029-one-of-variant2-added-integer");
export const Case_030_one_of_variant2_removed_integer: Story = createCaseStory("030-one-of-variant2-removed-integer");
export const Case_031_one_of_variant2_added_boolean: Story = createCaseStory("031-one-of-variant2-added-boolean");
export const Case_032_one_of_variant2_removed_boolean: Story = createCaseStory("032-one-of-variant2-removed-boolean");
export const Case_033_one_of_variant2_added_array: Story = createCaseStory("033-one-of-variant2-added-array");
export const Case_034_one_of_variant2_removed_array: Story = createCaseStory("034-one-of-variant2-removed-array");
export const Case_035_one_of_variant2_added_object: Story = createCaseStory("035-one-of-variant2-added-object");
export const Case_036_one_of_variant2_removed_object: Story = createCaseStory("036-one-of-variant2-removed-object");
