/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-additional-properties/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-additional-properties/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/object-additional-properties/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Object Additional Properties",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_add_additional_properties_false: Story = createCaseStory("001-add-additional-properties-false");
export const Case_002_remove_additional_properties_false: Story = createCaseStory("002-remove-additional-properties-false");
export const Case_003_add_additional_properties_type_string: Story = createCaseStory("003-add-additional-properties-type-string");
export const Case_004_remove_additional_properties_type_string: Story = createCaseStory("004-remove-additional-properties-type-string");
export const Case_005_change_additional_properties_string_to_false: Story = createCaseStory("005-change-additional-properties-string-to-false");
export const Case_006_change_additional_properties_false_to_string: Story = createCaseStory("006-change-additional-properties-false-to-string");
export const Case_007_add_additional_properties_type_number: Story = createCaseStory("007-add-additional-properties-type-number");
export const Case_008_remove_additional_properties_type_number: Story = createCaseStory("008-remove-additional-properties-type-number");
export const Case_009_change_additional_properties_number_to_false: Story = createCaseStory("009-change-additional-properties-number-to-false");
export const Case_010_change_additional_properties_false_to_number: Story = createCaseStory("010-change-additional-properties-false-to-number");
export const Case_011_add_additional_properties_type_integer: Story = createCaseStory("011-add-additional-properties-type-integer");
export const Case_012_remove_additional_properties_type_integer: Story = createCaseStory("012-remove-additional-properties-type-integer");
export const Case_013_change_additional_properties_integer_to_false: Story = createCaseStory("013-change-additional-properties-integer-to-false");
export const Case_014_change_additional_properties_false_to_integer: Story = createCaseStory("014-change-additional-properties-false-to-integer");
export const Case_015_add_additional_properties_type_boolean: Story = createCaseStory("015-add-additional-properties-type-boolean");
export const Case_016_remove_additional_properties_type_boolean: Story = createCaseStory("016-remove-additional-properties-type-boolean");
export const Case_017_change_additional_properties_boolean_to_false: Story = createCaseStory("017-change-additional-properties-boolean-to-false");
export const Case_018_change_additional_properties_false_to_boolean: Story = createCaseStory("018-change-additional-properties-false-to-boolean");
export const Case_019_add_additional_properties_type_array: Story = createCaseStory("019-add-additional-properties-type-array");
export const Case_020_remove_additional_properties_type_array: Story = createCaseStory("020-remove-additional-properties-type-array");
export const Case_021_change_additional_properties_array_to_false: Story = createCaseStory("021-change-additional-properties-array-to-false");
export const Case_022_change_additional_properties_false_to_array: Story = createCaseStory("022-change-additional-properties-false-to-array");
export const Case_023_add_additional_properties_type_object: Story = createCaseStory("023-add-additional-properties-type-object");
export const Case_024_remove_additional_properties_type_object: Story = createCaseStory("024-remove-additional-properties-type-object");
export const Case_025_change_additional_properties_object_to_false: Story = createCaseStory("025-change-additional-properties-object-to-false");
export const Case_026_change_additional_properties_false_to_object: Story = createCaseStory("026-change-additional-properties-false-to-object");
export const Case_027_one_of_object_variant_add_additional_properties_false: Story = createCaseStory("027-one-of-object-variant-add-additional-properties-false");
export const Case_028_one_of_object_variant_remove_additional_properties_false: Story = createCaseStory("028-one-of-object-variant-remove-additional-properties-false");
export const Case_029_one_of_object_variant_add_additional_properties_type_string: Story = createCaseStory("029-one-of-object-variant-add-additional-properties-type-string");
export const Case_030_one_of_object_variant_remove_additional_properties_type_string: Story = createCaseStory("030-one-of-object-variant-remove-additional-properties-type-string");
export const Case_031_one_of_object_variant_change_additional_properties_string_to_false: Story = createCaseStory("031-one-of-object-variant-change-additional-properties-string-to-false");
export const Case_032_one_of_object_variant_change_additional_properties_false_to_string: Story = createCaseStory("032-one-of-object-variant-change-additional-properties-false-to-string");
export const Case_033_one_of_object_variant_add_additional_properties_type_number: Story = createCaseStory("033-one-of-object-variant-add-additional-properties-type-number");
export const Case_034_one_of_object_variant_remove_additional_properties_type_number: Story = createCaseStory("034-one-of-object-variant-remove-additional-properties-type-number");
export const Case_035_one_of_object_variant_change_additional_properties_number_to_false: Story = createCaseStory("035-one-of-object-variant-change-additional-properties-number-to-false");
export const Case_036_one_of_object_variant_change_additional_properties_false_to_number: Story = createCaseStory("036-one-of-object-variant-change-additional-properties-false-to-number");
export const Case_037_one_of_object_variant_add_additional_properties_type_integer: Story = createCaseStory("037-one-of-object-variant-add-additional-properties-type-integer");
export const Case_038_one_of_object_variant_remove_additional_properties_type_integer: Story = createCaseStory("038-one-of-object-variant-remove-additional-properties-type-integer");
export const Case_039_one_of_object_variant_change_additional_properties_integer_to_false: Story = createCaseStory("039-one-of-object-variant-change-additional-properties-integer-to-false");
export const Case_040_one_of_object_variant_change_additional_properties_false_to_integer: Story = createCaseStory("040-one-of-object-variant-change-additional-properties-false-to-integer");
export const Case_041_one_of_object_variant_add_additional_properties_type_boolean: Story = createCaseStory("041-one-of-object-variant-add-additional-properties-type-boolean");
export const Case_042_one_of_object_variant_remove_additional_properties_type_boolean: Story = createCaseStory("042-one-of-object-variant-remove-additional-properties-type-boolean");
export const Case_043_one_of_object_variant_change_additional_properties_boolean_to_false: Story = createCaseStory("043-one-of-object-variant-change-additional-properties-boolean-to-false");
export const Case_044_one_of_object_variant_change_additional_properties_false_to_boolean: Story = createCaseStory("044-one-of-object-variant-change-additional-properties-false-to-boolean");
export const Case_045_one_of_object_variant_add_additional_properties_type_array: Story = createCaseStory("045-one-of-object-variant-add-additional-properties-type-array");
export const Case_046_one_of_object_variant_remove_additional_properties_type_array: Story = createCaseStory("046-one-of-object-variant-remove-additional-properties-type-array");
export const Case_047_one_of_object_variant_change_additional_properties_array_to_false: Story = createCaseStory("047-one-of-object-variant-change-additional-properties-array-to-false");
export const Case_048_one_of_object_variant_change_additional_properties_false_to_array: Story = createCaseStory("048-one-of-object-variant-change-additional-properties-false-to-array");
export const Case_049_one_of_object_variant_add_additional_properties_type_object: Story = createCaseStory("049-one-of-object-variant-add-additional-properties-type-object");
export const Case_050_one_of_object_variant_remove_additional_properties_type_object: Story = createCaseStory("050-one-of-object-variant-remove-additional-properties-type-object");
export const Case_051_one_of_object_variant_change_additional_properties_object_to_false: Story = createCaseStory("051-one-of-object-variant-change-additional-properties-object-to-false");
export const Case_052_one_of_object_variant_change_additional_properties_false_to_object: Story = createCaseStory("052-one-of-object-variant-change-additional-properties-false-to-object");
