/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/one-of-array-variant/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/one-of-array-variant/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/one-of-array-variant/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/OneOf Array Variant Samples",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_array_variant_add_one_indexed_item_string: Story = createCaseStory("001-array-variant-add-one-indexed-item-string");
export const Case_002_array_variant_remove_one_indexed_item_string: Story = createCaseStory("002-array-variant-remove-one-indexed-item-string");
export const Case_003_array_variant_add_two_indexed_items_string: Story = createCaseStory("003-array-variant-add-two-indexed-items-string");
export const Case_004_array_variant_remove_two_indexed_items_string: Story = createCaseStory("004-array-variant-remove-two-indexed-items-string");
export const Case_005_array_variant_added_string: Story = createCaseStory("005-array-variant-added-string");
export const Case_006_array_variant_removed_string: Story = createCaseStory("006-array-variant-removed-string");
export const Case_007_one_of_prop_added_string: Story = createCaseStory("007-one-of-prop-added-string");
export const Case_008_one_of_prop_removed_string: Story = createCaseStory("008-one-of-prop-removed-string");
export const Case_009_array_variant_add_one_indexed_item_number: Story = createCaseStory("009-array-variant-add-one-indexed-item-number");
export const Case_010_array_variant_remove_one_indexed_item_number: Story = createCaseStory("010-array-variant-remove-one-indexed-item-number");
export const Case_011_array_variant_add_two_indexed_items_number: Story = createCaseStory("011-array-variant-add-two-indexed-items-number");
export const Case_012_array_variant_remove_two_indexed_items_number: Story = createCaseStory("012-array-variant-remove-two-indexed-items-number");
export const Case_013_array_variant_added_number: Story = createCaseStory("013-array-variant-added-number");
export const Case_014_array_variant_removed_number: Story = createCaseStory("014-array-variant-removed-number");
export const Case_015_one_of_prop_added_number: Story = createCaseStory("015-one-of-prop-added-number");
export const Case_016_one_of_prop_removed_number: Story = createCaseStory("016-one-of-prop-removed-number");
export const Case_017_array_variant_add_one_indexed_item_integer: Story = createCaseStory("017-array-variant-add-one-indexed-item-integer");
export const Case_018_array_variant_remove_one_indexed_item_integer: Story = createCaseStory("018-array-variant-remove-one-indexed-item-integer");
export const Case_019_array_variant_add_two_indexed_items_integer: Story = createCaseStory("019-array-variant-add-two-indexed-items-integer");
export const Case_020_array_variant_remove_two_indexed_items_integer: Story = createCaseStory("020-array-variant-remove-two-indexed-items-integer");
export const Case_021_array_variant_added_integer: Story = createCaseStory("021-array-variant-added-integer");
export const Case_022_array_variant_removed_integer: Story = createCaseStory("022-array-variant-removed-integer");
export const Case_023_one_of_prop_added_integer: Story = createCaseStory("023-one-of-prop-added-integer");
export const Case_024_one_of_prop_removed_integer: Story = createCaseStory("024-one-of-prop-removed-integer");
export const Case_025_array_variant_add_one_indexed_item_boolean: Story = createCaseStory("025-array-variant-add-one-indexed-item-boolean");
export const Case_026_array_variant_remove_one_indexed_item_boolean: Story = createCaseStory("026-array-variant-remove-one-indexed-item-boolean");
export const Case_027_array_variant_add_two_indexed_items_boolean: Story = createCaseStory("027-array-variant-add-two-indexed-items-boolean");
export const Case_028_array_variant_remove_two_indexed_items_boolean: Story = createCaseStory("028-array-variant-remove-two-indexed-items-boolean");
export const Case_029_array_variant_added_boolean: Story = createCaseStory("029-array-variant-added-boolean");
export const Case_030_array_variant_removed_boolean: Story = createCaseStory("030-array-variant-removed-boolean");
export const Case_031_one_of_prop_added_boolean: Story = createCaseStory("031-one-of-prop-added-boolean");
export const Case_032_one_of_prop_removed_boolean: Story = createCaseStory("032-one-of-prop-removed-boolean");
export const Case_033_array_variant_add_one_indexed_item_array: Story = createCaseStory("033-array-variant-add-one-indexed-item-array");
export const Case_034_array_variant_remove_one_indexed_item_array: Story = createCaseStory("034-array-variant-remove-one-indexed-item-array");
export const Case_035_array_variant_add_two_indexed_items_array: Story = createCaseStory("035-array-variant-add-two-indexed-items-array");
export const Case_036_array_variant_remove_two_indexed_items_array: Story = createCaseStory("036-array-variant-remove-two-indexed-items-array");
export const Case_037_array_variant_added_array: Story = createCaseStory("037-array-variant-added-array");
export const Case_038_array_variant_removed_array: Story = createCaseStory("038-array-variant-removed-array");
export const Case_039_one_of_prop_added_array: Story = createCaseStory("039-one-of-prop-added-array");
export const Case_040_one_of_prop_removed_array: Story = createCaseStory("040-one-of-prop-removed-array");
export const Case_041_array_variant_add_one_indexed_item_object: Story = createCaseStory("041-array-variant-add-one-indexed-item-object");
export const Case_042_array_variant_remove_one_indexed_item_object: Story = createCaseStory("042-array-variant-remove-one-indexed-item-object");
export const Case_043_array_variant_add_two_indexed_items_object: Story = createCaseStory("043-array-variant-add-two-indexed-items-object");
export const Case_044_array_variant_remove_two_indexed_items_object: Story = createCaseStory("044-array-variant-remove-two-indexed-items-object");
export const Case_045_array_variant_added_object: Story = createCaseStory("045-array-variant-added-object");
export const Case_046_array_variant_removed_object: Story = createCaseStory("046-array-variant-removed-object");
export const Case_047_one_of_prop_added_object: Story = createCaseStory("047-one-of-prop-added-object");
export const Case_048_one_of_prop_removed_object: Story = createCaseStory("048-one-of-prop-removed-object");
