/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/one-of-object-variant/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/one-of-object-variant/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/one-of-object-variant/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/OneOf Object Variant Samples",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_object_variant_add_one_property_string: Story = createCaseStory("001-object-variant-add-one-property-string");
export const Case_002_object_variant_remove_one_property_string: Story = createCaseStory("002-object-variant-remove-one-property-string");
export const Case_003_object_variant_add_two_properties_string: Story = createCaseStory("003-object-variant-add-two-properties-string");
export const Case_004_object_variant_remove_two_properties_string: Story = createCaseStory("004-object-variant-remove-two-properties-string");
export const Case_005_object_variant_added_string: Story = createCaseStory("005-object-variant-added-string");
export const Case_006_object_variant_removed_string: Story = createCaseStory("006-object-variant-removed-string");
export const Case_007_one_of_prop_added_string: Story = createCaseStory("007-one-of-prop-added-string");
export const Case_008_one_of_prop_removed_string: Story = createCaseStory("008-one-of-prop-removed-string");
export const Case_009_object_variant_add_one_property_number: Story = createCaseStory("009-object-variant-add-one-property-number");
export const Case_010_object_variant_remove_one_property_number: Story = createCaseStory("010-object-variant-remove-one-property-number");
export const Case_011_object_variant_add_two_properties_number: Story = createCaseStory("011-object-variant-add-two-properties-number");
export const Case_012_object_variant_remove_two_properties_number: Story = createCaseStory("012-object-variant-remove-two-properties-number");
export const Case_013_object_variant_added_number: Story = createCaseStory("013-object-variant-added-number");
export const Case_014_object_variant_removed_number: Story = createCaseStory("014-object-variant-removed-number");
export const Case_015_one_of_prop_added_number: Story = createCaseStory("015-one-of-prop-added-number");
export const Case_016_one_of_prop_removed_number: Story = createCaseStory("016-one-of-prop-removed-number");
export const Case_017_object_variant_add_one_property_integer: Story = createCaseStory("017-object-variant-add-one-property-integer");
export const Case_018_object_variant_remove_one_property_integer: Story = createCaseStory("018-object-variant-remove-one-property-integer");
export const Case_019_object_variant_add_two_properties_integer: Story = createCaseStory("019-object-variant-add-two-properties-integer");
export const Case_020_object_variant_remove_two_properties_integer: Story = createCaseStory("020-object-variant-remove-two-properties-integer");
export const Case_021_object_variant_added_integer: Story = createCaseStory("021-object-variant-added-integer");
export const Case_022_object_variant_removed_integer: Story = createCaseStory("022-object-variant-removed-integer");
export const Case_023_one_of_prop_added_integer: Story = createCaseStory("023-one-of-prop-added-integer");
export const Case_024_one_of_prop_removed_integer: Story = createCaseStory("024-one-of-prop-removed-integer");
export const Case_025_object_variant_add_one_property_boolean: Story = createCaseStory("025-object-variant-add-one-property-boolean");
export const Case_026_object_variant_remove_one_property_boolean: Story = createCaseStory("026-object-variant-remove-one-property-boolean");
export const Case_027_object_variant_add_two_properties_boolean: Story = createCaseStory("027-object-variant-add-two-properties-boolean");
export const Case_028_object_variant_remove_two_properties_boolean: Story = createCaseStory("028-object-variant-remove-two-properties-boolean");
export const Case_029_object_variant_added_boolean: Story = createCaseStory("029-object-variant-added-boolean");
export const Case_030_object_variant_removed_boolean: Story = createCaseStory("030-object-variant-removed-boolean");
export const Case_031_one_of_prop_added_boolean: Story = createCaseStory("031-one-of-prop-added-boolean");
export const Case_032_one_of_prop_removed_boolean: Story = createCaseStory("032-one-of-prop-removed-boolean");
export const Case_033_object_variant_add_one_property_array: Story = createCaseStory("033-object-variant-add-one-property-array");
export const Case_034_object_variant_remove_one_property_array: Story = createCaseStory("034-object-variant-remove-one-property-array");
export const Case_035_object_variant_add_two_properties_array: Story = createCaseStory("035-object-variant-add-two-properties-array");
export const Case_036_object_variant_remove_two_properties_array: Story = createCaseStory("036-object-variant-remove-two-properties-array");
export const Case_037_object_variant_added_array: Story = createCaseStory("037-object-variant-added-array");
export const Case_038_object_variant_removed_array: Story = createCaseStory("038-object-variant-removed-array");
export const Case_039_one_of_prop_added_array: Story = createCaseStory("039-one-of-prop-added-array");
export const Case_040_one_of_prop_removed_array: Story = createCaseStory("040-one-of-prop-removed-array");
export const Case_041_object_variant_add_one_property_object: Story = createCaseStory("041-object-variant-add-one-property-object");
export const Case_042_object_variant_remove_one_property_object: Story = createCaseStory("042-object-variant-remove-one-property-object");
export const Case_043_object_variant_add_two_properties_object: Story = createCaseStory("043-object-variant-add-two-properties-object");
export const Case_044_object_variant_remove_two_properties_object: Story = createCaseStory("044-object-variant-remove-two-properties-object");
export const Case_045_object_variant_added_object: Story = createCaseStory("045-object-variant-added-object");
export const Case_046_object_variant_removed_object: Story = createCaseStory("046-object-variant-removed-object");
export const Case_047_one_of_prop_added_object: Story = createCaseStory("047-one-of-prop-added-object");
export const Case_048_one_of_prop_removed_object: Story = createCaseStory("048-one-of-prop-removed-object");
