/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-property-rename-suite.mjs
 * Edit together with src/it/json-schema-diffs-suite/property-rename.it-test.ts
 */
import { JsonSchemaDiffsViewer } from "@apihub/components/JsonSchemaViewer/JsonSchemaDiffsViewer";
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import { createSampleById } from "../utils/sample-cases";
import {
  createJsonSchemaDiffCaseStoryFactory,
  JSON_SCHEMA_DIFF_META_KEYS,
  JSON_SCHEMA_DIFFS_SUITE_EXPANDED_DEPTH,
  type JsonSchemaDiffCaseStoryComponentProps,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";
import { createParametersSchemaFromOpenApiPair } from "./parameters-schema-synthesis";

/**
 * Fixtures are OpenAPI documents, not JSON Schemas: `apiDiff` never renames a JSON Schema property,
 * so the viewer gets a schema synthesized from the operation's parameters, where a renamed path
 * parameter becomes a `rename` of its property key (see `parameters-schema-synthesis.ts`).
 */
const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/property-rename/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/property-rename/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleById = createSampleById(collectSampleCases(beforeFiles, afterFiles));

const PropertyRenameDiffsStory = ({ beforeYaml, afterYaml, hideUnchangedNodes }: JsonSchemaDiffCaseStoryComponentProps) => (
  <JsonSchemaDiffsViewer
    schema={createParametersSchemaFromOpenApiPair(beforeYaml, afterYaml)}
    expandedDepth={JSON_SCHEMA_DIFFS_SUITE_EXPANDED_DEPTH}
    diffMetaKeys={JSON_SCHEMA_DIFF_META_KEYS}
    hideUnchangedNodes={hideUnchangedNodes}
  />
);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Property Rename",
  component: PropertyRenameDiffsStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof PropertyRenameDiffsStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(PropertyRenameDiffsStory, sampleById);

export const Case_01_renamed_only: Story = createCaseStory("01-renamed-only");
export const Case_02_renamed_and_description_changed: Story = createCaseStory("02-renamed-and-description-changed");
export const Case_03_renamed_and_type_changed: Story = createCaseStory("03-renamed-and-type-changed");
export const Case_04_renamed_and_validation_changed: Story = createCaseStory("04-renamed-and-validation-changed");
export const Case_05_renamed_and_deprecated: Story = createCaseStory("05-renamed-and-deprecated");
export const Case_06_renamed_object_parameter: Story = createCaseStory("06-renamed-object-parameter");
export const Case_07_two_parameters_renamed: Story = createCaseStory("07-two-parameters-renamed");
export const Case_08_renamed_with_query_parameter_added: Story = createCaseStory("08-renamed-with-query-parameter-added");
export const Case_09_query_parameter_renamed_is_removed_and_added: Story = createCaseStory("09-query-parameter-renamed-is-removed-and-added");
