/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/string-validation/value-length/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/string-validation/value-length/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/string-validation/value-length/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/String Validation Value Length",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_min_length_added: Story = createCaseStory("001-min-length-added");
export const Case_002_min_length_removed: Story = createCaseStory("002-min-length-removed");
export const Case_003_min_length_replaced: Story = createCaseStory("003-min-length-replaced");
export const Case_004_max_length_added: Story = createCaseStory("004-max-length-added");
export const Case_005_max_length_removed: Story = createCaseStory("005-max-length-removed");
export const Case_006_max_length_replaced: Story = createCaseStory("006-max-length-replaced");
export const Case_007_min_max_length_added: Story = createCaseStory("007-min-max-length-added");
export const Case_008_min_max_length_removed: Story = createCaseStory("008-min-max-length-removed");
export const Case_009_min_length_added_max_length_removed: Story = createCaseStory("009-min-length-added-max-length-removed");
export const Case_010_min_length_removed_max_length_added: Story = createCaseStory("010-min-length-removed-max-length-added");
export const Case_011_both_lengths_replace_min: Story = createCaseStory("011-both-lengths-replace-min");
export const Case_012_both_lengths_replace_max: Story = createCaseStory("012-both-lengths-replace-max");
export const Case_013_both_lengths_replaced: Story = createCaseStory("013-both-lengths-replaced");
export const Case_014_unchanged_min_length: Story = createCaseStory("014-unchanged-min-length");
export const Case_015_unchanged_max_length: Story = createCaseStory("015-unchanged-max-length");
export const Case_016_unchanged_min_max_length: Story = createCaseStory("016-unchanged-min-max-length");
