/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/type-annotations-changes/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/type-annotations-changes/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/type-annotations-changes/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Type Annotations Changes Samples",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_title_added: Story = createCaseStory("001-title-added");
export const Case_002_title_removed: Story = createCaseStory("002-title-removed");
export const Case_003_title_replaced: Story = createCaseStory("003-title-replaced");
export const Case_004_format_added: Story = createCaseStory("004-format-added");
export const Case_005_format_removed: Story = createCaseStory("005-format-removed");
export const Case_006_format_replaced: Story = createCaseStory("006-format-replaced");
export const Case_007_title_added_format_added: Story = createCaseStory("007-title-added-format-added");
export const Case_008_title_added_format_removed: Story = createCaseStory("008-title-added-format-removed");
export const Case_009_title_added_format_replaced: Story = createCaseStory("009-title-added-format-replaced");
export const Case_010_title_removed_format_added: Story = createCaseStory("010-title-removed-format-added");
export const Case_011_title_removed_format_removed: Story = createCaseStory("011-title-removed-format-removed");
export const Case_012_title_removed_format_replaced: Story = createCaseStory("012-title-removed-format-replaced");
export const Case_013_title_replaced_format_added: Story = createCaseStory("013-title-replaced-format-added");
export const Case_014_title_replaced_format_removed: Story = createCaseStory("014-title-replaced-format-removed");
export const Case_015_title_replaced_format_replaced: Story = createCaseStory("015-title-replaced-format-replaced");
