/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/type-flags/
 */
import type { Meta, StoryObj } from "@storybook/react";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import {
  JsonSchemaDiffSamplesStory,
  createJsonSchemaDiffCaseStoryFactory,
  createJsonSchemaDiffSampleById,
  jsonSchemaDiffSampleReadonlyArgTypes,
} from "./json-schema-diffs-utils";

const beforeFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/type-flags/*/before.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/json-schema-diffs/type-changes/type-flags/*/after.yaml",
  { as: "raw", eager: true },
) as Record<string, string>;

const sampleCases = collectSampleCases(beforeFiles, afterFiles);
const sampleById = createJsonSchemaDiffSampleById(sampleCases);

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "JSON Schema Diffs Suite/Type Flags Samples",
  component: JsonSchemaDiffSamplesStory,
  argTypes: jsonSchemaDiffSampleReadonlyArgTypes,
} satisfies Meta<typeof JsonSchemaDiffSamplesStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = createJsonSchemaDiffCaseStoryFactory(
  JsonSchemaDiffSamplesStory,
  sampleById,
);

export const Case_001_read_only_added: Story = createCaseStory("001-read-only-added");
export const Case_002_read_only_removed: Story = createCaseStory("002-read-only-removed");
export const Case_003_write_only_added: Story = createCaseStory("003-write-only-added");
export const Case_004_write_only_removed: Story = createCaseStory("004-write-only-removed");
export const Case_005_deprecated_added: Story = createCaseStory("005-deprecated-added");
export const Case_006_deprecated_removed: Story = createCaseStory("006-deprecated-removed");
export const Case_007_required_added: Story = createCaseStory("007-required-added");
export const Case_008_required_removed: Story = createCaseStory("008-required-removed");
export const Case_009_unchanged_read_only: Story = createCaseStory("009-unchanged-read-only");
export const Case_010_unchanged_write_only: Story = createCaseStory("010-unchanged-write-only");
export const Case_011_unchanged_deprecated: Story = createCaseStory("011-unchanged-deprecated");
export const Case_012_unchanged_required_field: Story = createCaseStory("012-unchanged-required-field");
export const Case_013_unchanged_required_optional: Story = createCaseStory("013-unchanged-required-optional");
