// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import { createSampleById } from "../utils/sample-cases";
import { OPENAPI_STORY_ARG_TYPES, OPENAPI_STORY_DEFAULT_ARGS } from "../openapi-suite/openapi-story-args";
import { OpenApiDiffSampleStory } from "./OpenApiDiffSampleStory";

const beforeFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/operation/*/before.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/operation/*/after.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const sampleById = createSampleById(collectSampleCases(beforeFiles, afterFiles));

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "OpenAPI Operation Diffs Suite/Operation",
  component: OpenApiDiffSampleStory,
  argTypes: OPENAPI_STORY_ARG_TYPES,
  args: OPENAPI_STORY_DEFAULT_ARGS,
} satisfies Meta<typeof OpenApiDiffSampleStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = (caseId: string): Story => {
  const sample = sampleById[caseId];
  if (!sample) {
    throw new Error(`Sample case not found: ${caseId}`);
  }
  return { name: caseId, args: { caseId, beforeYaml: sample.beforeYaml, afterYaml: sample.afterYaml } };
};

export const Case_01_summary_added: Story = createCaseStory("01-summary-added");
export const Case_02_summary_removed: Story = createCaseStory("02-summary-removed");
export const Case_03_summary_changed: Story = createCaseStory("03-summary-changed");
export const Case_04_operation_id_added: Story = createCaseStory("04-operation-id-added");
export const Case_05_operation_id_removed: Story = createCaseStory("05-operation-id-removed");
export const Case_06_operation_id_changed: Story = createCaseStory("06-operation-id-changed");
export const Case_07_description_added: Story = createCaseStory("07-description-added");
export const Case_08_description_removed: Story = createCaseStory("08-description-removed");
export const Case_09_description_changed: Story = createCaseStory("09-description-changed");
export const Case_10_external_docs_added: Story = createCaseStory("10-external-docs-added");
export const Case_11_external_docs_removed: Story = createCaseStory("11-external-docs-removed");
export const Case_12_external_docs_url_changed: Story = createCaseStory("12-external-docs-url-changed");
export const Case_13_external_docs_description_changed: Story = createCaseStory("13-external-docs-description-changed");
export const Case_14_deprecated_added: Story = createCaseStory("14-deprecated-added");
export const Case_15_deprecated_removed: Story = createCaseStory("15-deprecated-removed");
export const Case_16_deprecated_added_without_summary: Story = createCaseStory("16-deprecated-added-without-summary");
export const Case_17_deprecated_removed_without_summary: Story = createCaseStory("17-deprecated-removed-without-summary");
export const Case_18_extension_added: Story = createCaseStory("18-extension-added");
export const Case_19_extension_removed: Story = createCaseStory("19-extension-removed");
export const Case_20_extension_changed: Story = createCaseStory("20-extension-changed");
export const Case_21_extensions_added: Story = createCaseStory("21-extensions-added");
export const Case_22_extensions_removed: Story = createCaseStory("22-extensions-removed");
export const Case_23_operation_added: Story = createCaseStory("23-operation-added");
export const Case_24_operation_removed: Story = createCaseStory("24-operation-removed");
