// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import { createSampleById } from "../utils/sample-cases";
import { OPENAPI_STORY_ARG_TYPES, OPENAPI_STORY_DEFAULT_ARGS } from "../openapi-suite/openapi-story-args";
import { OpenApiDiffSampleStory } from "./OpenApiDiffSampleStory";

const beforeFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/request-body/*/before.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/request-body/*/after.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const sampleById = createSampleById(collectSampleCases(beforeFiles, afterFiles));

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "OpenAPI Operation Diffs Suite/Request Body",
  component: OpenApiDiffSampleStory,
  argTypes: OPENAPI_STORY_ARG_TYPES,
  args: OPENAPI_STORY_DEFAULT_ARGS,
} satisfies Meta<typeof OpenApiDiffSampleStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = (caseId: string): Story => {
  const sample = sampleById[caseId];
  if (!sample) {
    throw new Error(`Sample case not found: ${caseId}`);
  }
  return { name: caseId, args: { caseId, beforeYaml: sample.beforeYaml, afterYaml: sample.afterYaml } };
};

export const Case_01_body_added: Story = createCaseStory("01-body-added");
export const Case_02_body_removed: Story = createCaseStory("02-body-removed");
export const Case_03_required_added: Story = createCaseStory("03-required-added");
export const Case_04_required_removed: Story = createCaseStory("04-required-removed");
export const Case_05_description_added: Story = createCaseStory("05-description-added");
export const Case_06_description_removed: Story = createCaseStory("06-description-removed");
export const Case_07_description_changed: Story = createCaseStory("07-description-changed");
export const Case_08_media_type_added: Story = createCaseStory("08-media-type-added");
export const Case_09_media_type_removed: Story = createCaseStory("09-media-type-removed");
export const Case_10_media_type_renamed: Story = createCaseStory("10-media-type-renamed");
export const Case_11_only_media_type_added: Story = createCaseStory("11-only-media-type-added");
export const Case_12_only_media_type_removed: Story = createCaseStory("12-only-media-type-removed");
export const Case_13_media_type_added_description_kept: Story = createCaseStory("13-media-type-added-description-kept");
export const Case_14_media_type_removed_description_kept: Story = createCaseStory("14-media-type-removed-description-kept");
export const Case_15_schema_added: Story = createCaseStory("15-schema-added");
export const Case_16_schema_removed: Story = createCaseStory("16-schema-removed");
export const Case_17_schema_property_added: Story = createCaseStory("17-schema-property-added");
export const Case_18_schema_property_removed: Story = createCaseStory("18-schema-property-removed");
export const Case_19_schema_type_changed: Story = createCaseStory("19-schema-type-changed");
export const Case_20_body_extension_added: Story = createCaseStory("20-body-extension-added");
export const Case_21_body_extension_removed: Story = createCaseStory("21-body-extension-removed");
export const Case_22_media_type_extension_added: Story = createCaseStory("22-media-type-extension-added");
export const Case_23_media_type_extension_removed: Story = createCaseStory("23-media-type-extension-removed");
export const Case_24_extensions_changed: Story = createCaseStory("24-extensions-changed");
export const Case_25_media_type_extension_shadows_schema_root: Story = createCaseStory("25-media-type-extension-shadows-schema-root");
