// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import { createSampleById } from "../utils/sample-cases";
import { OPENAPI_STORY_ARG_TYPES, OPENAPI_STORY_DEFAULT_ARGS } from "../openapi-suite/openapi-story-args";
import { OpenApiDiffSampleStory } from "./OpenApiDiffSampleStory";

const beforeFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/response-body/*/before.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/response-body/*/after.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const sampleById = createSampleById(collectSampleCases(beforeFiles, afterFiles));

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "OpenAPI Operation Diffs Suite/Response Body",
  component: OpenApiDiffSampleStory,
  argTypes: OPENAPI_STORY_ARG_TYPES,
  args: OPENAPI_STORY_DEFAULT_ARGS,
} satisfies Meta<typeof OpenApiDiffSampleStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = (caseId: string): Story => {
  const sample = sampleById[caseId];
  if (!sample) {
    throw new Error(`Sample case not found: ${caseId}`);
  }
  return { name: caseId, args: { caseId, beforeYaml: sample.beforeYaml, afterYaml: sample.afterYaml } };
};

export const Case_01_body_added: Story = createCaseStory("01-body-added");
export const Case_02_body_removed: Story = createCaseStory("02-body-removed");
export const Case_08_media_type_added: Story = createCaseStory("08-media-type-added");
export const Case_09_media_type_removed: Story = createCaseStory("09-media-type-removed");
export const Case_10_media_type_renamed: Story = createCaseStory("10-media-type-renamed");
export const Case_15_schema_added: Story = createCaseStory("15-schema-added");
export const Case_16_schema_removed: Story = createCaseStory("16-schema-removed");
export const Case_17_schema_property_added: Story = createCaseStory("17-schema-property-added");
export const Case_18_schema_property_removed: Story = createCaseStory("18-schema-property-removed");
export const Case_19_schema_type_changed: Story = createCaseStory("19-schema-type-changed");
export const Case_22_media_type_extension_added: Story = createCaseStory("22-media-type-extension-added");
export const Case_23_media_type_extension_removed: Story = createCaseStory("23-media-type-extension-removed");
export const Case_25_media_type_extension_shadows_schema_root: Story = createCaseStory("25-media-type-extension-shadows-schema-root");
