// Generated by bin/generate-openapi-diffs-suite.mjs - do not edit by hand.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { collectSampleCases } from "../utils/diffs-samples-cases";
import { createSampleById } from "../utils/sample-cases";
import { OPENAPI_STORY_ARG_TYPES, OPENAPI_STORY_DEFAULT_ARGS } from "../openapi-suite/openapi-story-args";
import { OpenApiDiffSampleStory } from "./OpenApiDiffSampleStory";

const beforeFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/response-headers/*/before.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const afterFiles = import.meta.glob(
  "../../../../samples/openapi-diffs/response-headers/*/after.yaml",
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const sampleById = createSampleById(collectSampleCases(beforeFiles, afterFiles));

// eslint-disable-next-line storybook/story-exports
const meta = {
  title: "OpenAPI Operation Diffs Suite/Response Headers",
  component: OpenApiDiffSampleStory,
  argTypes: OPENAPI_STORY_ARG_TYPES,
  args: OPENAPI_STORY_DEFAULT_ARGS,
} satisfies Meta<typeof OpenApiDiffSampleStory>;

export default meta;

type Story = StoryObj<typeof meta>;

const createCaseStory = (caseId: string): Story => {
  const sample = sampleById[caseId];
  if (!sample) {
    throw new Error(`Sample case not found: ${caseId}`);
  }
  return { name: caseId, args: { caseId, beforeYaml: sample.beforeYaml, afterYaml: sample.afterYaml } };
};

export const Case_01_entry_added: Story = createCaseStory("01-entry-added");
export const Case_02_entry_removed: Story = createCaseStory("02-entry-removed");
export const Case_03_entry_renamed: Story = createCaseStory("03-entry-renamed");
export const Case_04_required_added: Story = createCaseStory("04-required-added");
export const Case_05_required_removed: Story = createCaseStory("05-required-removed");
export const Case_06_description_added: Story = createCaseStory("06-description-added");
export const Case_07_description_removed: Story = createCaseStory("07-description-removed");
export const Case_08_description_changed: Story = createCaseStory("08-description-changed");
export const Case_09_deprecated_added: Story = createCaseStory("09-deprecated-added");
export const Case_10_deprecated_removed: Story = createCaseStory("10-deprecated-removed");
export const Case_11_schema_to_content: Story = createCaseStory("11-schema-to-content");
export const Case_12_content_to_schema: Story = createCaseStory("12-content-to-schema");
export const Case_13_content_media_type_renamed: Story = createCaseStory("13-content-media-type-renamed");
export const Case_14_extension_added: Story = createCaseStory("14-extension-added");
export const Case_15_extension_removed: Story = createCaseStory("15-extension-removed");
export const Case_16_extension_changed: Story = createCaseStory("16-extension-changed");
export const Case_17_extension_moved_to_schema: Story = createCaseStory("17-extension-moved-to-schema");
export const Case_18_extension_moved_to_entry: Story = createCaseStory("18-extension-moved-to-entry");
export const Case_19_all_added: Story = createCaseStory("19-all-added");
export const Case_20_all_removed: Story = createCaseStory("20-all-removed");
export const Case_21_description_moved_entry_to_schema: Story = createCaseStory("21-description-moved-entry-to-schema");
export const Case_22_description_moved_schema_to_entry: Story = createCaseStory("22-description-moved-schema-to-entry");
export const Case_23_description_entry_removed_schema_added: Story = createCaseStory("23-description-entry-removed-schema-added");
export const Case_24_description_schema_removed_entry_added: Story = createCaseStory("24-description-schema-removed-entry-added");
export const Case_25_description_both_places_changed: Story = createCaseStory("25-description-both-places-changed");
export const Case_26_description_schema_changed_under_entry: Story = createCaseStory("26-description-schema-changed-under-entry");
