import type { Meta, StoryObj } from '@storybook/react';
import { GraphQLCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<GraphQLCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AddFieldDescriptionInObjectTypeFromUnionType: Story;
export declare const AddNewFieldInObjectTypeFromUnionType: Story;
export declare const AddObjectTypeInUnionType: Story;
export declare const ChangeFieldTypeInObjectTypeFromUnionType: Story;
export declare const ChangeObjectTypeInUnionType: Story;
export declare const DeleteFieldDescriptionInObjectTypeFromUnionType: Story;
export declare const MarkMandatoryFieldAsOptionalInObjectTypeFromUnionType: Story;
export declare const MarkOptionalFieldAsMandatoryInObjectTypeFromUnionType: Story;
export declare const RemoveFieldInObjectTypeFromUnionType: Story;
export declare const RemoveObjectTypeFromUnionType: Story;
export declare const UpdateFieldDescriptionInObjectTypeFromUnionType: Story;
