CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE public.projects (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  name character varying(1000) NOT NULL
    CONSTRAINT projects_name_length CHECK (char_length(name) >= 1),
  description text,
  CONSTRAINT projects_name_key UNIQUE (name)
);
