CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE public.users_plus_idx (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  login character varying(30) NOT NULL
    CONSTRAINT users_plus_idx_login_length CHECK (char_length(login) >= 3),
  password character(32) NOT NULL,
  email character varying(200)
    CONSTRAINT users_plus_idx_email_length CHECK (char_length(email) >= 6),
  enabled boolean NOT NULL DEFAULT true,
  registration_date timestamp without time zone NOT NULL,
  CONSTRAINT users_plus_idx_login_key UNIQUE (login)
);

CREATE INDEX users_login_idx ON public.users_plus_idx (login);

CREATE INDEX users_email_idx ON public.users_plus_idx (email);

CREATE INDEX users_complex_idx ON public.users_plus_idx (login, email);
