import type { Meta, StoryObj } from '@storybook/react';
import { GraphQLCompatibilitySuiteStoryArgs } from '../utils/compatibility-suite-utils';
declare const meta: Meta<GraphQLCompatibilitySuiteStoryArgs>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const AddDefaultValueOfArgument: Story;
export declare const AddDefaultValueOfRequiredArgument: Story;
export declare const AddDescriptionForArgument: Story;
export declare const AddDescriptionForEnumType: Story;
export declare const AddDescriptionForEnumValue: Story;
export declare const AddEnumValueInEnumArgument: Story;
export declare const AddOptionalArgument: Story;
export declare const AddSecondArgument: Story;
export declare const ChangeDefaultValueOfArgument: Story;
export declare const ChangeDefaultValueOfRequiredArgument: Story;
export declare const ChangeDescriptionForEnumType: Story;
export declare const ChangeDescriptionForEnumValue: Story;
export declare const ChangeTypeOfArgument: Story;
export declare const DeleteDescriptionForEnumType: Story;
export declare const DeleteDescriptionForEnumValue: Story;
export declare const DeleteDescriptionOfArgument: Story;
export declare const MarkMandatoryArgumentAsOptional: Story;
export declare const MarkOptionalArgumentAsMandatory: Story;
export declare const RemoveArgument: Story;
export declare const RemoveDefaultValueOfArgument: Story;
export declare const RemoveDefaultValueOfRequiredArgument: Story;
export declare const RemoveEnumValueInEnumArgument: Story;
export declare const RemoveOneArgument: Story;
export declare const UpdateDescriptionOfArgument: Story;
