import { AsyncApiTreeNode } from '../../../../next-data-model/src/model/async-api/types/aliases';
import { AsyncApiTreeNodeKinds } from '../../../../next-data-model/src/model/async-api/types/node-kind';
export declare function isMessageNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE>;
export declare function isMessageSectionSelectorNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_SECTION_SELECTOR>;
export declare function isMessageContentNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_CONTENT>;
export declare function isMessageContentHeadersNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_HEADERS>;
export declare function isMessageContentPayloadNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_PAYLOAD>;
export declare function isMessageChannelNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_CHANNEL>;
export declare function isMessageChannelParametersNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_CHANNEL_PARAMETERS>;
export declare function isMessageOperationNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_OPERATION>;
export declare function isExtensionsNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.EXTENSIONS>;
export declare function isBindingsNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.BINDINGS>;
export declare function isBindingNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.BINDING>;
export declare function isMessageSectionNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.MESSAGE_CONTENT | typeof AsyncApiTreeNodeKinds.MESSAGE_CHANNEL | typeof AsyncApiTreeNodeKinds.MESSAGE_OPERATION>;
export declare function isServersNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.SERVERS>;
export declare function isServerNode(node: AsyncApiTreeNode): node is AsyncApiTreeNode<typeof AsyncApiTreeNodeKinds.SERVER>;
