/**
 * Generated by packages/api-doc-viewer/bin/generate-json-schema-type-changes-samples.mjs
 * Fixtures: packages/samples/json-schema-diffs/type-changes/object-additional-properties/
 */
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, hideUnchangedNodes, }: import("./json-schema-diffs-oas-3-1-utils").JsonSchemaDiffCaseStoryComponentProps) => import('../../../../../node_modules/react/jsx-runtime').JSX.Element;
    argTypes: {
        beforeYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        afterYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
        hideUnchangedNodes: {
            control: {
                type: "boolean";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_053_add_property_names: Story;
export declare const Case_054_remove_property_names: Story;
export declare const Case_055_property_names_enum_value_added: Story;
export declare const Case_056_property_names_enum_value_removed: Story;
export declare const Case_057_property_names_enum_value_replaced: Story;
export declare const Case_058_property_names_enum_value_added_and_replaced: Story;
export declare const Case_059_property_names_enum_value_removed_and_replaced: Story;
export declare const Case_060_property_names_enum_value_added_and_removed: Story;
export declare const Case_061_property_names_enum_values_both_replaced: Story;
export declare const Case_062_property_names_enum_values_swapped: Story;
export declare const Case_063_property_names_unchanged: Story;
