import { StoryObj } from '@storybook/react-vite';
declare const meta: {
    title: string;
    component: ({ beforeYaml, afterYaml, hideUnchangedNodes }: import('./OpenApiDiffSampleStory').OpenApiDiffSampleStoryProps) => import("react").JSX.Element;
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Case_01_query_parameter_added: Story;
export declare const Case_02_all_headers_removed: Story;
export declare const Case_03_mixed_header_changes: Story;
export declare const Case_04_parameter_required_changed: Story;
export declare const Case_05_parameter_moved_query_to_header: Story;
export declare const Case_06_body_media_type_added: Story;
export declare const Case_07_body_media_type_renamed: Story;
export declare const Case_08_body_description_and_schema_changed: Story;
export declare const Case_09_request_body_added: Story;
export declare const Case_10_request_body_became_optional: Story;
export declare const Case_11_description_moved_entry_to_schema: Story;
export declare const Case_12_description_entry_removed_schema_added: Story;
export declare const Case_13_description_schema_removed_entry_added: Story;
export declare const Case_14_description_both_places_changed: Story;
export declare const Case_15_description_schema_changed_under_entry: Story;
export declare const Case_16_parameter_schema_to_content: Story;
export declare const Case_17_parameter_content_media_type_renamed: Story;
export declare const Case_18_parameter_content_media_type_replaced: Story;
export declare const Case_19_body_only_media_type_removed: Story;
export declare const Case_20_body_only_schema_removed: Story;
export declare const Case_21_body_only_schema_added: Story;
export declare const Case_22_body_media_type_removed_description_kept: Story;
export declare const Case_23_body_removed: Story;
export declare const Case_24_parameter_extension_added_and_changed: Story;
export declare const Case_25_parameter_extension_moved_to_schema: Story;
export declare const Case_26_parameter_extension_nested_change: Story;
export declare const Case_27_body_and_media_type_extensions_changed: Story;
export declare const Case_28_media_type_extension_shadows_schema_root: Story;
