name: frontend-ci 

on:
  push:
    branches:
      - release
      - hotfix
      - develop
      - feature/*
      - bugfix/*      
    tags:
      - '**'

jobs:
  call-frontend-ci-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/frontend-ci.yaml@bugfix/npm-ci-hangs-up 
    with:
      npm_log_level: "silly"
