name: Storybook CD Workflow

on:
  workflow_dispatch:

  delete:
    branches:      

jobs: 
  call-storybook-cd-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/storybook-cd.yaml@main 
