import { type JsonSchemaSamplesStoryObj } from "./json-schema-samples-common";
declare const meta: {
    id: string;
    title: string;
    component: (_props: import("./json-schema-samples-common").JsonSchemaCaseStoryComponentProps) => null;
    argTypes: {
        caseId: {
            control: {
                disable: true;
            };
            table: {
                disable: true;
            };
        };
        sampleYaml: {
            control: {
                type: "text";
            };
            table: {
                category: string;
            };
            description: string;
        };
    };
};
export default meta;
type Story = JsonSchemaSamplesStoryObj;
export declare const Case_001_string_schema: Story;
export declare const Case_002_number_schema: Story;
export declare const Case_003_integer_schema: Story;
export declare const Case_004_boolean_schema: Story;
export declare const Case_005_array_schema: Story;
export declare const Case_006_object_schema: Story;
export declare const Case_007_all_types_schema: Story;
export declare const Case_008_string_MyString_NULL_schema: Story;
export declare const Case_009_string_NULL_ISODateTime_schema: Story;
export declare const Case_010_string_MyString_ISODateTime_schema: Story;
export declare const Case_011_number_MyNumber_NULL_schema: Story;
export declare const Case_012_number_NULL_ISODateTime_schema: Story;
export declare const Case_013_number_MyNumber_ISODateTime_schema: Story;
export declare const Case_014_integer_MyInteger_NULL_schema: Story;
export declare const Case_015_integer_NULL_ISODateTime_schema: Story;
export declare const Case_016_integer_MyInteger_ISODateTime_schema: Story;
export declare const Case_017_boolean_MyBoolean_NULL_schema: Story;
export declare const Case_018_boolean_NULL_ISODateTime_schema: Story;
export declare const Case_019_boolean_MyBoolean_ISODateTime_schema: Story;
export declare const Case_020_array_MyArray_NULL_schema: Story;
export declare const Case_021_array_NULL_ISODateTime_schema: Story;
export declare const Case_022_array_MyArray_ISODateTime_schema: Story;
export declare const Case_023_object_MyObject_NULL_schema: Story;
export declare const Case_024_object_NULL_ISODateTime_schema: Story;
export declare const Case_025_object_MyObject_ISODateTime_schema: Story;
export declare const Case_026_string_schema_one_of: Story;
export declare const Case_027_number_schema_one_of: Story;
export declare const Case_028_integer_schema_one_of: Story;
export declare const Case_029_boolean_schema_one_of: Story;
export declare const Case_030_array_schema_one_of: Story;
export declare const Case_031_object_schema_one_of: Story;
export declare const Case_032_string_schema_any_of: Story;
export declare const Case_033_number_schema_any_of: Story;
export declare const Case_034_integer_schema_any_of: Story;
export declare const Case_035_boolean_schema_any_of: Story;
export declare const Case_036_array_schema_any_of: Story;
export declare const Case_037_object_schema_any_of: Story;
export declare const Case_038_string_schema_all_of: Story;
export declare const Case_039_number_schema_all_of: Story;
export declare const Case_040_integer_schema_all_of: Story;
export declare const Case_041_boolean_schema_all_of: Story;
export declare const Case_042_array_schema_all_of: Story;
export declare const Case_043_object_schema_all_of: Story;
export declare const Case_044_string_schema_one_of_one_of: Story;
export declare const Case_045_number_schema_one_of_one_of: Story;
export declare const Case_046_integer_schema_one_of_one_of: Story;
export declare const Case_047_boolean_schema_one_of_one_of: Story;
export declare const Case_048_array_schema_one_of_one_of: Story;
export declare const Case_049_object_schema_one_of_one_of: Story;
export declare const Case_050_string_schema_one_of_any_of: Story;
export declare const Case_051_number_schema_one_of_any_of: Story;
export declare const Case_052_integer_schema_one_of_any_of: Story;
export declare const Case_053_boolean_schema_one_of_any_of: Story;
export declare const Case_054_array_schema_one_of_any_of: Story;
export declare const Case_055_object_schema_one_of_any_of: Story;
export declare const Case_056_string_schema_one_of_all_of: Story;
export declare const Case_057_number_schema_one_of_all_of: Story;
export declare const Case_058_integer_schema_one_of_all_of: Story;
export declare const Case_059_boolean_schema_one_of_all_of: Story;
export declare const Case_060_array_schema_one_of_all_of: Story;
export declare const Case_061_object_schema_one_of_all_of: Story;
export declare const Case_062_string_schema_any_of_one_of: Story;
export declare const Case_063_number_schema_any_of_one_of: Story;
export declare const Case_064_integer_schema_any_of_one_of: Story;
export declare const Case_065_boolean_schema_any_of_one_of: Story;
export declare const Case_066_array_schema_any_of_one_of: Story;
export declare const Case_067_object_schema_any_of_one_of: Story;
export declare const Case_068_string_schema_any_of_any_of: Story;
export declare const Case_069_number_schema_any_of_any_of: Story;
export declare const Case_070_integer_schema_any_of_any_of: Story;
export declare const Case_071_boolean_schema_any_of_any_of: Story;
export declare const Case_072_array_schema_any_of_any_of: Story;
export declare const Case_073_object_schema_any_of_any_of: Story;
export declare const Case_074_string_schema_any_of_all_of: Story;
export declare const Case_075_number_schema_any_of_all_of: Story;
export declare const Case_076_integer_schema_any_of_all_of: Story;
export declare const Case_077_boolean_schema_any_of_all_of: Story;
export declare const Case_078_array_schema_any_of_all_of: Story;
export declare const Case_079_object_schema_any_of_all_of: Story;
export declare const Case_080_string_schema_all_of_one_of: Story;
export declare const Case_081_number_schema_all_of_one_of: Story;
export declare const Case_082_integer_schema_all_of_one_of: Story;
export declare const Case_083_boolean_schema_all_of_one_of: Story;
export declare const Case_084_array_schema_all_of_one_of: Story;
export declare const Case_085_object_schema_all_of_one_of: Story;
export declare const Case_086_string_schema_all_of_any_of: Story;
export declare const Case_087_number_schema_all_of_any_of: Story;
export declare const Case_088_integer_schema_all_of_any_of: Story;
export declare const Case_089_boolean_schema_all_of_any_of: Story;
export declare const Case_090_array_schema_all_of_any_of: Story;
export declare const Case_091_object_schema_all_of_any_of: Story;
export declare const Case_092_string_schema_all_of_all_of: Story;
export declare const Case_093_number_schema_all_of_all_of: Story;
export declare const Case_094_integer_schema_all_of_all_of: Story;
export declare const Case_095_boolean_schema_all_of_all_of: Story;
export declare const Case_096_array_schema_all_of_all_of: Story;
export declare const Case_097_object_schema_all_of_all_of: Story;
